/* ============================================================
   Robotics & Perception Engineer — Interview Prep Curriculum
   8-week plan | Python + C++ | Intermediate
   Edit this file to add/remove topics. The tracker reads it directly.
   ============================================================ */

const CURRICULUM = [
  {
    week: 1,
    title: "LeetCode Patterns & Core Techniques",
    goal: "The pattern cheat sheet for coding rounds: two pointers, sliding window, BFS, DFS, binary search, divide & conquer, dynamic programming, backtracking, heaps and union-find — when to reach for each, a reusable template, and the complexity. Recognize the pattern, not the problem.",
    lecture: "lecture.html?week=1",
    topics: [
      "Picking the technique from the problem's shape (the decision reflex)",
      "Two pointers & sliding window (O(n) array/substring scans)",
      "BFS vs. DFS — shortest path vs. reachability/components/topo-sort",
      "Binary search, including search-on-the-answer",
      "Divide & conquer vs. dynamic programming (overlapping subproblems)",
      "Designing a DP: state, transition, base case, fill order",
      "Backtracking, heaps/top-k, and union-find",
    ],
    leetcode: [
      { name: "3Sum", pid: "3sum", url: "https://leetcode.com/problems/3sum/", diff: "Medium", tag: "Two Pointers" },
      { name: "Longest Substring Without Repeating Characters", pid: "longest-substring-no-repeat", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", diff: "Medium", tag: "Sliding Window" },
      { name: "Rotting Oranges", pid: "rotting-oranges", url: "https://leetcode.com/problems/rotting-oranges/", diff: "Medium", tag: "BFS" },
      { name: "Course Schedule II", pid: "course-schedule-ii", url: "https://leetcode.com/problems/course-schedule-ii/", diff: "Medium", tag: "DFS/Topo Sort" },
      { name: "Search in Rotated Sorted Array", pid: "search-in-rotated-sorted-array", url: "https://leetcode.com/problems/search-in-rotated-sorted-array/", diff: "Medium", tag: "Binary Search" },
      { name: "Merge k Sorted Lists", pid: "merge-k-sorted-lists", url: "https://leetcode.com/problems/merge-k-sorted-lists/", diff: "Hard", tag: "Divide & Conquer/Heap" },
      { name: "Coin Change", pid: "coin-change", url: "https://leetcode.com/problems/coin-change/", diff: "Medium", tag: "DP" },
      { name: "Subsets", pid: "subsets", url: "https://leetcode.com/problems/subsets/", diff: "Medium", tag: "Backtracking" },
      { name: "Top K Frequent Elements", pid: "top-k-frequent", url: "https://leetcode.com/problems/top-k-frequent-elements/", diff: "Medium", tag: "Heap/Top-K" },
      { name: "Number of Provinces", pid: "number-of-provinces", url: "https://leetcode.com/problems/number-of-provinces/", diff: "Medium", tag: "Union-Find" },
      { name: "Jump Game", pid: "jump-game", url: "https://leetcode.com/problems/jump-game/", diff: "Medium", tag: "Greedy" },
    ],
    robotics: [],
  },
  {
    week: 2,
    title: "Math Foundations",
    goal: "Rebuild the linear algebra, probability, and optimization muscles every perception algorithm leans on.",
    lecture: "lecture.html?week=2",
    topics: [
      "Vectors, matrices, norms, dot/cross products",
      "Eigenvalues, eigenvectors, SVD (geometric meaning)",
      "Least squares (normal equations + SVD solution)",
      "Probability: Bayes rule, Gaussians, covariance",
      "Gradient descent, Gauss-Newton, Levenberg-Marquardt",
    ],
    leetcode: [
      { name: "Two Sum", pid: "two-sum", url: "https://leetcode.com/problems/two-sum/", diff: "Easy", tag: "Arrays/Hash" },
      { name: "Maximum Subarray", pid: "maximum-subarray", url: "https://leetcode.com/problems/maximum-subarray/", diff: "Medium", tag: "DP/Kadane" },
      { name: "Product of Array Except Self", pid: "product-except-self", url: "https://leetcode.com/problems/product-of-array-except-self/", diff: "Medium", tag: "Arrays" },
    ],
    robotics: [
      { name: "Least-Squares Line Fit", pid: "rob-least-squares-line", diff: "Easy", tag: "Linear Algebra", file: "coding-practice/robotics/w1_least_squares.py" },
      { name: "Covariance & Mahalanobis Distance", pid: "rob-covariance-mahalanobis", diff: "Medium", tag: "Probability", file: "coding-practice/robotics/w1_covariance.py" },
    ],
  },
  {
    week: 3,
    title: "3D Geometry & Rigid-Body Transforms",
    goal: "Master rotations, quaternions, and SE(3) — the language of every robot pose.",
    lecture: "lecture.html?week=3",
    topics: [
      "Rotation matrices, properties of SO(3)",
      "Euler angles & gimbal lock",
      "Axis-angle and the exponential map",
      "Quaternions: composition, slerp, pitfalls",
      "Homogeneous coordinates & SE(3) transforms",
      "Frame conventions (body, world, camera, sensor)",
    ],
    leetcode: [
      { name: "Rotate Image", pid: "rotate-image", url: "https://leetcode.com/problems/rotate-image/", diff: "Medium", tag: "Matrix" },
      { name: "Spiral Matrix", pid: "spiral-matrix", url: "https://leetcode.com/problems/spiral-matrix/", diff: "Medium", tag: "Matrix" },
      { name: "Set Matrix Zeroes", pid: "set-matrix-zeroes", url: "https://leetcode.com/problems/set-matrix-zeroes/", diff: "Medium", tag: "Matrix" },
    ],
    robotics: [
      { name: "Rotate a Vector by a Quaternion", pid: "rob-quaternion-rotate", diff: "Easy", tag: "3D Geometry", file: "coding-practice/robotics/w2_rotations.py" },
      { name: "Compose SE(3) and Transform a Point", pid: "rob-transform-point", diff: "Medium", tag: "3D Geometry", file: "coding-practice/robotics/w2_transform_chain.py" },
    ],
  },
  {
    week: 4,
    title: "Camera Models & Classical Image Processing",
    goal: "Understand how 3D becomes pixels, and the filtering/feature toolkit on top of it.",
    lecture: "lecture.html?week=4",
    topics: [
      "Pinhole model, intrinsics K, extrinsics",
      "Lens distortion (radial/tangential) & undistortion",
      "Camera calibration (Zhang's method)",
      "Convolution, Gaussian/box blur, separable filters",
      "Image gradients, Sobel, Laplacian",
      "Image pyramids & scale space",
    ],
    leetcode: [
      { name: "Image Smoother", pid: "image-smoother", url: "https://leetcode.com/problems/image-smoother/", diff: "Easy", tag: "Matrix/Conv" },
      { name: "Number of Islands", pid: "number-of-islands", url: "https://leetcode.com/problems/number-of-islands/", diff: "Medium", tag: "BFS/DFS/CC" },
      { name: "Pacific Atlantic Water Flow", pid: "pacific-atlantic", url: "https://leetcode.com/problems/pacific-atlantic-water-flow/", diff: "Medium", tag: "Grid DFS" },
    ],
    robotics: [
      { name: "2D Cross-Correlation", pid: "rob-convolution-2d", diff: "Easy", tag: "Image Processing", file: "coding-practice/robotics/w3_convolution.py" },
      { name: "Project a 3D Point to a Pixel", pid: "rob-project-point", diff: "Easy", tag: "Camera Model", file: "coding-practice/robotics/w3_projection.py" },
    ],
  },
  {
    week: 5,
    title: "Features & Multi-View Geometry",
    goal: "Detect, describe, and match features; recover geometry between views.",
    lecture: "lecture.html?week=5",
    topics: [
      "Harris corners, FAST, blob detectors",
      "Descriptors: SIFT, ORB, BRIEF; matching + ratio test",
      "RANSAC for robust model fitting",
      "Epipolar geometry: fundamental & essential matrix",
      "Homography & the 8-point / 5-point algorithms",
      "Triangulation and PnP",
      "Bundle adjustment (reprojection error)",
    ],
    leetcode: [
      { name: "Max Points on a Line", pid: "max-points-on-a-line", url: "https://leetcode.com/problems/max-points-on-a-line/", diff: "Hard", tag: "Geometry" },
      { name: "K Closest Points to Origin", pid: "k-closest-points", url: "https://leetcode.com/problems/k-closest-points-to-origin/", diff: "Medium", tag: "Heap" },
      { name: "Find K Closest Elements", pid: "find-k-closest-elements", url: "https://leetcode.com/problems/find-k-closest-elements/", diff: "Medium", tag: "Binary Search" },
    ],
    robotics: [
      { name: "RANSAC Line — Max Inliers", pid: "rob-ransac-line-inliers", diff: "Medium", tag: "Robust Fitting", file: "coding-practice/robotics/w4_ransac.py" },
      { name: "2D Rigid Point-Set Alignment (Kabsch)", pid: "rob-rigid-align-2d", diff: "Medium", tag: "Registration", file: "coding-practice/robotics/w4_homography_fmatrix.py" },
    ],
  },
  {
    week: 6,
    title: "State Estimation & Filtering",
    goal: "Fuse noisy sensors over time: Bayes filter, KF/EKF/UKF, particle filter.",
    lecture: "lecture.html?week=6",
    topics: [
      "Recursive Bayes filter (predict/update)",
      "Kalman filter derivation & assumptions",
      "Extended KF: linearization, Jacobians",
      "Unscented KF: sigma points",
      "Particle filter / Monte Carlo localization",
      "Tuning Q, R; observability & consistency (NEES)",
    ],
    leetcode: [
      { name: "Moving Average from Data Stream", pid: "moving-average", url: "https://leetcode.com/problems/moving-average-from-data-stream/", diff: "Easy", tag: "Stream" },
      { name: "Sliding Window Maximum", pid: "sliding-window-maximum", url: "https://leetcode.com/problems/sliding-window-maximum/", diff: "Hard", tag: "Deque" },
      { name: "Find Median from Data Stream", pid: "find-median-from-data-stream", url: "https://leetcode.com/problems/find-median-from-data-stream/", diff: "Hard", tag: "Heaps" },
    ],
    robotics: [
      { name: "1D Kalman Filter (scalar)", pid: "rob-kalman-1d", diff: "Medium", tag: "State Estimation", file: "coding-practice/robotics/w5_kalman_1d.py" },
      { name: "Inverse-Variance Sensor Fusion", pid: "rob-measurement-fusion", diff: "Easy", tag: "Sensor Fusion" },
    ],
  },
  {
    week: 7,
    title: "SLAM, Odometry & Sensor Fusion",
    goal: "Tie geometry + estimation together into mapping and localization systems.",
    lecture: "lecture.html?week=7",
    topics: [
      "SLAM problem: front-end vs back-end",
      "Visual odometry pipeline (feature & direct)",
      "Pose-graph optimization & loop closure",
      "Factor graphs (GTSAM/g2o mental model)",
      "LiDAR odometry & ICP (point-to-point/plane)",
      "Visual-inertial odometry (IMU preintegration idea)",
    ],
    leetcode: [
      { name: "Course Schedule", pid: "course-schedule", url: "https://leetcode.com/problems/course-schedule/", diff: "Medium", tag: "Graph/Topo" },
      { name: "Network Delay Time", pid: "network-delay-time", url: "https://leetcode.com/problems/network-delay-time/", diff: "Medium", tag: "Dijkstra" },
      { name: "Graph Valid Tree", pid: "graph-valid-tree", url: "https://leetcode.com/problems/graph-valid-tree/", diff: "Medium", tag: "Union-Find" },
    ],
    robotics: [
      { name: "ICP — One Iteration (2D)", pid: "rob-icp-2d-step", diff: "Hard", tag: "SLAM / Registration", file: "coding-practice/robotics/w6_icp.py" },
      { name: "1D Pose-Graph Optimization", pid: "rob-pose-graph-1d", diff: "Hard", tag: "SLAM / Optimization", file: "coding-practice/robotics/w6_pose_graph.py" },
    ],
  },
  {
    week: 8,
    title: "Deep Learning for Perception",
    goal: "Modern neural perception: detection, segmentation, 3D, and point clouds.",
    lecture: "lecture.html?week=8",
    topics: [
      "CNN building blocks; receptive field; BN/dropout",
      "Object detection (one-stage vs two-stage, anchors, NMS)",
      "Semantic & instance segmentation (U-Net, Mask R-CNN)",
      "3D detection & BEV; LiDAR nets (PointNet/voxel)",
      "Metrics: IoU, mAP, precision/recall curves",
      "Sensor fusion & calibration for learned models",
    ],
    leetcode: [
      { name: "Maximal Square", pid: "maximal-square", url: "https://leetcode.com/problems/maximal-square/", diff: "Medium", tag: "DP/Grid" },
      { name: "Word Ladder", pid: "word-ladder", url: "https://leetcode.com/problems/word-ladder/", diff: "Hard", tag: "BFS" },
      { name: "LRU Cache", pid: "lru-cache", url: "https://leetcode.com/problems/lru-cache/", diff: "Medium", tag: "Design" },
    ],
    robotics: [
      { name: "IoU + Non-Max Suppression", pid: "rob-iou-nms", diff: "Medium", tag: "Detection", file: "coding-practice/robotics/w7_nms_iou.py" },
      { name: "Average Precision (detection)", pid: "rob-average-precision", diff: "Hard", tag: "Detection Metrics", file: "coding-practice/robotics/w7_map.py" },
    ],
  },
  {
    week: 9,
    title: "Systems, ROS & Mock Interviews",
    goal: "Wire it into real systems and rehearse the interview itself.",
    lecture: "lecture.html?week=9",
    topics: [
      "ROS/ROS2 concepts: nodes, topics, TF, time sync",
      "Real-time, latency, threading, memory in C++",
      "Coordinate frames & calibration in a full stack",
      "System design: 'design a perception pipeline for X'",
      "Behavioral stories (STAR) + project deep-dives",
      "2-3 timed mock interviews (coding + domain)",
    ],
    leetcode: [
      { name: "Merge Intervals", pid: "merge-intervals", url: "https://leetcode.com/problems/merge-intervals/", diff: "Medium", tag: "Intervals" },
      { name: "Design Circular Queue", pid: "design-circular-queue", url: "https://leetcode.com/problems/design-circular-queue/", diff: "Medium", tag: "Ring buffer" },
      { name: "Time-Based Key-Value Store", pid: "time-based-key-value-store", url: "https://leetcode.com/problems/time-based-key-value-store/", diff: "Medium", tag: "Design" },
    ],
    robotics: [
      { name: "Sensor Ring Buffer", pid: "rob-ring-buffer", diff: "Easy", tag: "Systems / Design", file: "coding-practice/robotics/w8_ring_buffer.py" },
      { name: "Nearest-Timestamp Sensor Sync", pid: "rob-time-sync", diff: "Medium", tag: "Systems / Sync", file: "coding-practice/robotics/w8_time_sync.py" },
    ],
  },
  {
    week: 10,
    title: "C++ for Robotics",
    goal: "The C++ idioms you're expected to speak fluently — RAII, ownership, move semantics, real-time memory, and concurrency. Plus a real-time systems problem; re-solve earlier ones with the C++ tab too.",
    lecture: "lecture.html?week=10",
    topics: [
      "RAII & deterministic resource management",
      "Smart pointers: unique_ptr / shared_ptr / weak_ptr",
      "Move semantics & the Rule of 0/3/5",
      "const correctness; references vs pointers",
      "STL containers & their complexity",
      "Memory, cache locality & real-time (no heap in hot loops)",
      "Concurrency: threads, mutex, atomics, data races",
      "Eigen / PCL / OpenCV / ROS2 & CMake basics",
    ],
    leetcode: [],
    robotics: [
      { name: "Real-Time Frame Ingest Buffer", pid: "rob-frame-ingest", diff: "Medium", tag: "Systems / Real-Time" },
    ],
  },
  {
    week: 11,
    title: "Zipline — Aerial Perception & 3D Reconstruction",
    goal: "Role-specific prep for Zipline's Droid team: cloud-side perception that builds 3D + semantic world models from satellite/aerial imagery, predicts deliverability, and ships priors to the onboard stack. Question bank, worked deep-dives (bundle adjustment, DSM vs DTM, semantic-to-3D fusion, deliverability calibration, coordinate frames, eval without ground truth), and solved coding problems.",
    lecture: "lecture.html?week=11",
    topics: [
      "SfM / MVS / NeRF / 3DGS for aerial reconstruction",
      "Bundle adjustment with GPS/IMU/RTK pose priors",
      "DSM vs DTM vs nDSM — landing surface & clearance",
      "Semantic segmentation of delivery zones; 2D→3D label fusion",
      "Deliverability prediction & probability calibration",
      "Coordinate frames: WGS84 / ECEF / ENU / camera; geoid pitfalls",
      "Safety-critical eval without 3D ground truth; per-hazard recall gates",
    ],
    leetcode: [
      { name: "Path With Minimum Effort", pid: "path-with-minimum-effort", url: "https://leetcode.com/problems/path-with-minimum-effort/", diff: "Medium", tag: "Grid Dijkstra" },
      { name: "Shortest Path in Binary Matrix", pid: "shortest-path-in-binary-matrix", url: "https://leetcode.com/problems/shortest-path-in-binary-matrix/", diff: "Medium", tag: "Grid BFS/A*" },
    ],
    robotics: [],
  },
  {
    week: 12,
    title: "Zipline — Aerial Perception: Detailed Answers",
    goal: "Full worked answers to every question in the Week 11 question bank — the 'what a strong senior/staff answer actually says' companion. Covers SfM/MVS tradeoffs, BA with pose priors, DSM/DTM, semantic-to-3D fusion, bootstrapping with little labeled data, domain shift, the onboarding pipeline & onboard trust contract, production MLE judgment, and safety-critical eval with per-hazard gates.",
    lecture: "lecture.html?week=12",
    topics: [
      "A1 — Reconstruction & multi-view geometry, answered",
      "A2 — Semantic segmentation & learned perception, answered",
      "A3 — Cloud-side pipeline & world models, answered",
      "A4 — Production MLE judgment (SOTA vs classical, scale, versioning)",
      "A5 — Safety-critical evaluation & per-hazard recall gates",
      "Every answer: technique → failure mode → safety consequence",
    ],
    leetcode: [],
    robotics: [],
  },
  {
    week: 13,
    title: "BEV Transformers & Attention",
    goal: "Build the transformer from scratch — tokens, scaled dot-product attention, self vs. cross vs. multi-head, positional encoding — then see exactly how BEVFormer/DETR3D reuse it for multi-camera 3D perception. Diagrams, PyTorch/NumPy code, and the attention questions interviewers actually ask.",
    lecture: "lecture.html?week=13",
    topics: [
      "Tokens, embeddings & the transformer block (attention + FFN + residual/LayerNorm)",
      "Scaled dot-product attention and the √dₖ scaling",
      "Self-attention vs. cross-attention (same math, different Q/K/V source)",
      "Multi-head attention & positional encoding",
      "ViT & DETR: images as tokens, set prediction without NMS",
      "BEVFormer spatial cross-attention + temporal self-attention",
      "Deformable attention & keeping O(N²) tractable for multi-camera BEV",
    ],
    leetcode: [],
    robotics: [
      { name: "Lift-Splat BEV Pooling", pid: "rob-bev-splat", diff: "Medium", tag: "BEV / 3D Perception" },
      { name: "Project 3D Points to Camera", pid: "rob-bev-project", diff: "Medium", tag: "BEV / 3D Perception" },
    ],
  },
  {
    week: 14,
    title: "Concurrency for Robotics (async/await + sensor streams)",
    goal: "Python async/await done right for data/perception infra — diagnose I/O- vs CPU-bound, run concurrent tasks with sequential steps, bound concurrency with semaphores and backpressure. Then the same reasoning applied to multi-rate sensor streams, time sync, and ROS2 executors — and where async is the wrong tool (the hard-real-time control loop).",
    lecture: "lecture.html?week=14",
    topics: [
      "The two worlds: hard-real-time C++/ROS2 vs offline Python/asyncio infra",
      "async/await, gather, create_task; total time = max, not sum",
      "Diagnosing I/O- vs CPU-bound (and the asyncio.to_thread / process-pool escape)",
      "The pipeline problem: concurrent tasks with sequential steps",
      "Bounded concurrency: semaphores, bounded queues, backpressure, failure handling",
      "async vs threads vs multiprocessing vs message queue",
      "Multi-rate sensor streams, time sync (ExactTime/ApproximateTime), ROS2 executors",
    ],
    leetcode: [],
    robotics: [],
  },
  {
    week: 15,
    title: "Sensor Fusion & Multi-Object Tracking (Autonomous Trucking)",
    goal: "Turn per-sensor detections into stable, evaluated tracks for a highway-speed truck. Tracking-by-detection end to end: fusion architecture (early vs late), data association (gating, GNN/Hungarian, JPDA, MHT), track lifecycle (birth, M-of-N confirm, coasting through occlusion, death), and fusing camera/radar/lidar/thermal/IMU by their complementary failure modes. Plus learned+classical fusion, tracking metrics (MOTA/IDF1/HOTA) and their blind spots, and the trucking domain (long stopping distance, long range, articulation). Prep for Kodiak — Senior Autonomy Engineer, Perception.",
    lecture: "lecture.html?week=15",
    topics: [
      "Tracking-by-detection: predict → associate → update → lifecycle",
      "Fusion architecture: early vs mid (BEV) vs late/track-level; graceful degradation",
      "Data association: Mahalanobis gating, GNN/Hungarian, JPDA, MHT",
      "Track lifecycle: birth, M-of-N confirm, coasting through occlusion, death",
      "Per-sensor roles: camera, radar (Doppler), lidar, thermal, IMU; calibration & time sync",
      "Learned + classical: calibrated NN covariance into a filter, OOD fallbacks",
      "Metrics: MOTA/MOTP/IDF1/HOTA blind spots; range-stratified evaluation; pipeline debugging",
      "Trucking domain: stopping distance, long-range reliability, trailer articulation",
    ],
    leetcode: [],
    robotics: [],
  },
  {
    week: 16,
    title: "Perception Coding Drills (KF · IoU/NMS · Association · SORT)",
    goal: "The write-the-code companion to weeks 6 and 15. The six perception coding problems that recur in sensor-fusion/MOT interviews, each with approach, a clean reference solution, complexity, and the follow-ups interviewers push on: a 1D + constant-velocity Kalman filter, IoU + NMS, greedy vs Hungarian data association, a minimal SORT tracker, Mahalanobis gating, and two-pointer time-sync of sensor streams. Prep for Kodiak — Senior Autonomy Engineer, Perception.",
    lecture: "lecture.html?week=16",
    topics: [
      "Kalman filter from scratch: 1D then constant-velocity (Joseph-form update)",
      "IoU + Non-Max Suppression; the clamp bug and soft-NMS",
      "Data association: greedy vs Hungarian (linear_sum_assignment); gating first",
      "Minimal SORT tracker: predict → associate → update → lifecycle",
      "Mahalanobis gating with a chi-square threshold",
      "Time-sync two sensor streams with two pointers (O(n+m))",
      "Interview reflex: brute force + complexity out loud, then edge cases",
    ],
    leetcode: [],
    robotics: [],
  },
  {
    week: 17,
    title: "Applied Intuition — Company Problem Set",
    goal: "The coding questions reported for Applied Intuition interviews (sourced from interviewsolver.com), all solvable in the in-site editor (Python or C++). A broad mix — trees, backtracking, DP, binary search, greedy/heap, string, math, and design — reflecting a generalist AV-software bar rather than one pattern. Three (Reorganize String, Insert/Delete/GetRandom, Snake Game) are adapted to deterministic I/O so the exact judge works; the adaptation is noted in each statement.",
    lecture: "lecture.html?week=17",
    topics: [
      "Trees: All Nodes Distance K (BFS + parent links), Diameter (DFS)",
      "Backtracking & DP: Combination Sum, Unique Paths II",
      "Binary search: Search Insert Position, Koko Eating Bananas, Kth Smallest in Sorted Matrix",
      "Greedy / heap: Reorganize String, Construct String With Repeat Limit",
      "String / hashing: One Swap Equal, String Compression, Rank Teams by Votes",
      "Math: kth Factor of n, Fraction to Recurring Decimal",
      "Design: Snake Game, multiset GetRandom bookkeeping",
    ],
    leetcode: [
      { name: "All Nodes Distance K in Binary Tree", pid: "all-nodes-distance-k", url: "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/", diff: "Medium", tag: "Tree / BFS" },
      { name: "Diameter of Binary Tree", pid: "diameter-of-binary-tree", url: "https://leetcode.com/problems/diameter-of-binary-tree/", diff: "Easy", tag: "Tree / DFS" },
      { name: "Combination Sum", pid: "combination-sum", url: "https://leetcode.com/problems/combination-sum/", diff: "Medium", tag: "Backtracking" },
      { name: "Insert Delete GetRandom O(1) - Duplicates", pid: "insert-delete-getrandom-duplicates", url: "https://leetcode.com/problems/insert-delete-getrandom-o1-duplicates-allowed/", diff: "Hard", tag: "Design" },
      { name: "Check if One String Swap Can Make Strings Equal", pid: "check-string-swap", url: "https://leetcode.com/problems/check-if-one-string-swap-can-make-strings-equal/", diff: "Easy", tag: "String" },
      { name: "Unique Paths II", pid: "unique-paths-ii", url: "https://leetcode.com/problems/unique-paths-ii/", diff: "Medium", tag: "DP" },
      { name: "Nested List Weight Sum II", pid: "nested-list-weight-sum-ii", url: "https://leetcode.com/problems/nested-list-weight-sum-ii/", diff: "Medium", tag: "DFS" },
      { name: "Merge k Sorted Lists", pid: "merge-k-sorted-lists", url: "https://leetcode.com/problems/merge-k-sorted-lists/", diff: "Hard", tag: "Heap / D&C" },
      { name: "String Compression", pid: "string-compression", url: "https://leetcode.com/problems/string-compression/", diff: "Medium", tag: "Two Pointers" },
      { name: "Minimum Absolute Difference", pid: "minimum-absolute-difference", url: "https://leetcode.com/problems/minimum-absolute-difference/", diff: "Easy", tag: "Sorting" },
      { name: "Search Insert Position", pid: "search-insert-position", url: "https://leetcode.com/problems/search-insert-position/", diff: "Easy", tag: "Binary Search" },
      { name: "Rotate Image", pid: "rotate-image", url: "https://leetcode.com/problems/rotate-image/", diff: "Medium", tag: "Matrix" },
      { name: "Design Snake Game", pid: "design-snake-game", url: "https://leetcode.com/problems/design-snake-game/", diff: "Medium", tag: "Design" },
      { name: "Reorganize String", pid: "reorganize-string", url: "https://leetcode.com/problems/reorganize-string/", diff: "Medium", tag: "Greedy / Heap" },
      { name: "Construct String With Repeat Limit", pid: "construct-string-repeat-limit", url: "https://leetcode.com/problems/construct-string-with-repeat-limit/", diff: "Medium", tag: "Greedy / Heap" },
      { name: "Koko Eating Bananas", pid: "koko-eating-bananas", url: "https://leetcode.com/problems/koko-eating-bananas/", diff: "Medium", tag: "Binary Search" },
      { name: "The kth Factor of n", pid: "kth-factor-of-n", url: "https://leetcode.com/problems/the-kth-factor-of-n/", diff: "Medium", tag: "Math" },
      { name: "Fraction to Recurring Decimal", pid: "fraction-to-recurring-decimal", url: "https://leetcode.com/problems/fraction-to-recurring-decimal/", diff: "Medium", tag: "Math" },
      { name: "Kth Smallest Element in a Sorted Matrix", pid: "kth-smallest-in-sorted-matrix", url: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/", diff: "Medium", tag: "Binary Search" },
      { name: "Rank Teams by Votes", pid: "rank-teams-by-votes", url: "https://leetcode.com/problems/rank-teams-by-votes/", diff: "Medium", tag: "Sorting" },
      { name: "Longest Substring Without Repeating Characters", pid: "longest-substring-no-repeat", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", diff: "Medium", tag: "Sliding Window" },
    ],
    robotics: [],
  },
];

if (typeof module !== "undefined") module.exports = CURRICULUM;
