/* AUTO-GENERATED by gen_problems.py. Expected outputs verified by running
   reference solutions locally. Edit gen_problems.py and rerun to change. */
const PROBLEMS = [
  {
    "id": "two-sum",
    "title": "Two Sum",
    "diff": "Easy",
    "pattern": "Arrays / Hashing",
    "week": 1,
    "statement": "<p>Given an array of integers and a target, return the <b>indices</b> (0-based) of the two numbers that add up to the target. Exactly one solution exists; return the indices in ascending order.</p>",
    "inputFormat": "Line 1: n. Line 2: n integers. Line 3: target.",
    "outputFormat": "The two indices, space-separated, ascending.",
    "tests": [
      {
        "input": "4\n2 7 11 15\n9\n",
        "expected": "0 1\n",
        "sample": true
      },
      {
        "input": "3\n3 2 4\n6\n",
        "expected": "1 2\n",
        "sample": true
      },
      {
        "input": "2\n3 3\n6\n",
        "expected": "0 1\n",
        "sample": false
      },
      {
        "input": "5\n-1 -2 -3 -4 -5\n-8\n",
        "expected": "2 4\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    arr = list(map(int, data[1:1+n]))\n    target = int(data[1+n])\n    # TODO: print the two indices\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<int> a(n);\n    for (auto& x : a) cin >> x;\n    int target; cin >> target;\n    // TODO: print the two indices\n    return 0;\n}\n"
    }
  },
  {
    "id": "maximum-subarray",
    "title": "Maximum Subarray",
    "diff": "Medium",
    "pattern": "DP / Kadane",
    "week": 1,
    "statement": "<p>Find the contiguous subarray with the largest sum and return that sum.</p>",
    "inputFormat": "Line 1: n. Line 2: n integers.",
    "outputFormat": "The maximum subarray sum.",
    "tests": [
      {
        "input": "9\n-2 1 -3 4 -1 2 1 -5 4\n",
        "expected": "6\n",
        "sample": true
      },
      {
        "input": "1\n1\n",
        "expected": "1\n",
        "sample": true
      },
      {
        "input": "5\n5 4 -1 7 8\n",
        "expected": "23\n",
        "sample": false
      },
      {
        "input": "4\n-3 -2 -5 -1\n",
        "expected": "-1\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    arr = list(map(int, data[1:1+n]))\n    # TODO: print the maximum subarray sum\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<long long> a(n);\n    for (auto& x : a) cin >> x;\n    // TODO: print the maximum subarray sum\n    return 0;\n}\n"
    }
  },
  {
    "id": "product-except-self",
    "title": "Product of Array Except Self",
    "diff": "Medium",
    "pattern": "Arrays / Prefix",
    "week": 1,
    "statement": "<p>Return an array where each element is the product of all the others, <b>without using division</b>. O(n) time.</p>",
    "inputFormat": "Line 1: n. Line 2: n integers.",
    "outputFormat": "n integers (the answer), space-separated.",
    "tests": [
      {
        "input": "4\n1 2 3 4\n",
        "expected": "24 12 8 6\n",
        "sample": true
      },
      {
        "input": "5\n-1 1 0 -3 3\n",
        "expected": "0 0 9 0 0\n",
        "sample": true
      },
      {
        "input": "2\n2 3\n",
        "expected": "3 2\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    arr = list(map(int, data[1:1+n]))\n    # TODO: print the result array\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<long long> a(n);\n    for (auto& x : a) cin >> x;\n    // TODO: print the result array\n    return 0;\n}\n"
    }
  },
  {
    "id": "rotate-image",
    "title": "Rotate Image",
    "diff": "Medium",
    "pattern": "Matrix",
    "week": 2,
    "statement": "<p>Rotate an n\u00d7n matrix by 90\u00b0 <b>clockwise</b> and print the result.</p>",
    "inputFormat": "Line 1: n. Next n lines: n integers each.",
    "outputFormat": "The rotated matrix, n lines of n integers.",
    "tests": [
      {
        "input": "3\n1 2 3\n4 5 6\n7 8 9\n",
        "expected": "7 4 1\n8 5 2\n9 6 3\n",
        "sample": true
      },
      {
        "input": "2\n1 2\n3 4\n",
        "expected": "3 1\n4 2\n",
        "sample": true
      },
      {
        "input": "1\n7\n",
        "expected": "7\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    vals = list(map(int, data[1:1+n*n]))\n    m = [vals[i*n:(i+1)*n] for i in range(n)]\n    # TODO: rotate 90 deg clockwise and print\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<vector<int>> m(n, vector<int>(n));\n    for (auto& r : m) for (auto& x : r) cin >> x;\n    // TODO: rotate 90 deg clockwise and print\n    return 0;\n}\n"
    }
  },
  {
    "id": "spiral-matrix",
    "title": "Spiral Matrix",
    "diff": "Medium",
    "pattern": "Matrix",
    "week": 2,
    "statement": "<p>Return all elements of the matrix in <b>spiral order</b> (clockwise from top-left).</p>",
    "inputFormat": "Line 1: rows cols. Next rows lines: cols integers each.",
    "outputFormat": "All elements in spiral order, space-separated on one line.",
    "tests": [
      {
        "input": "3 3\n1 2 3\n4 5 6\n7 8 9\n",
        "expected": "1 2 3 6 9 8 7 4 5\n",
        "sample": true
      },
      {
        "input": "3 4\n1 2 3 4\n5 6 7 8\n9 10 11 12\n",
        "expected": "1 2 3 4 8 12 11 10 9 5 6 7\n",
        "sample": true
      },
      {
        "input": "1 1\n5\n",
        "expected": "5\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    rows = int(data[0]); cols = int(data[1])\n    vals = list(map(int, data[2:2+rows*cols]))\n    m = [vals[i*cols:(i+1)*cols] for i in range(rows)]\n    # TODO: print spiral order\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int rows, cols; cin >> rows >> cols;\n    vector<vector<int>> m(rows, vector<int>(cols));\n    for (auto& r : m) for (auto& x : r) cin >> x;\n    // TODO: print spiral order\n    return 0;\n}\n"
    }
  },
  {
    "id": "number-of-islands",
    "title": "Number of Islands",
    "diff": "Medium",
    "pattern": "Grid BFS/DFS",
    "week": 3,
    "statement": "<p>Count the islands in a grid of <code>'1'</code> (land) and <code>'0'</code> (water). Cells connect 4-directionally.</p>",
    "inputFormat": "Line 1: rows cols. Next rows lines: a string of cols characters ('0'/'1').",
    "outputFormat": "The number of islands.",
    "tests": [
      {
        "input": "4 5\n11110\n11010\n11000\n00000\n",
        "expected": "1\n",
        "sample": true
      },
      {
        "input": "3 3\n101\n010\n101\n",
        "expected": "5\n",
        "sample": true
      },
      {
        "input": "1 1\n0\n",
        "expected": "0\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split('\\n')\n    rows, cols = map(int, data[0].split())\n    grid = [list(data[1+i].strip()) for i in range(rows)]\n    # TODO: print the island count\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int rows, cols; cin >> rows >> cols;\n    vector<string> g(rows);\n    for (auto& s : g) cin >> s;\n    // TODO: print the island count\n    return 0;\n}\n"
    }
  },
  {
    "id": "path-with-minimum-effort",
    "title": "Path With Minimum Effort",
    "diff": "Medium",
    "pattern": "Grid Dijkstra",
    "week": 10,
    "statement": "<p>Given a <code>rows x cols</code> grid of integer heights, find a path from the top-left to the bottom-right cell moving <b>4-directionally</b>. A path's <b>effort</b> is the maximum absolute height difference between any two consecutive cells on it. Return the minimum possible effort.</p>",
    "inputFormat": "Line 1: rows cols. Next rows lines: cols integers each.",
    "outputFormat": "The minimum effort (an integer).",
    "tests": [
      {
        "input": "3 3\n1 2 2\n3 8 2\n5 3 5\n",
        "expected": "2\n",
        "sample": true
      },
      {
        "input": "3 3\n1 2 3\n3 8 4\n5 3 5\n",
        "expected": "1\n",
        "sample": true
      },
      {
        "input": "5 5\n1 2 1 1 1\n1 2 1 2 1\n1 2 1 2 1\n1 2 1 2 1\n1 1 1 2 1\n",
        "expected": "0\n",
        "sample": false
      },
      {
        "input": "1 1\n42\n",
        "expected": "0\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    rows = int(data[0]); cols = int(data[1])\n    vals = list(map(int, data[2:2+rows*cols]))\n    h = [vals[i*cols:(i+1)*cols] for i in range(rows)]\n    # TODO: print the minimum effort\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int rows, cols; cin >> rows >> cols;\n    vector<vector<int>> h(rows, vector<int>(cols));\n    for (auto& r : h) for (auto& x : r) cin >> x;\n    // TODO: print the minimum effort\n    return 0;\n}\n"
    }
  },
  {
    "id": "shortest-path-in-binary-matrix",
    "title": "Shortest Path in Binary Matrix",
    "diff": "Medium",
    "pattern": "Grid BFS/A*",
    "week": 10,
    "statement": "<p>In an <code>n x n</code> grid of <code>'0'</code> (clear) and <code>'1'</code> (blocked), find the length of the shortest <b>clear path</b> from the top-left to the bottom-right cell, moving <b>8-directionally</b> between clear cells. Path length is the number of visited cells. Return <code>-1</code> if no path exists.</p>",
    "inputFormat": "Line 1: n. Next n lines: a string of n characters ('0'/'1').",
    "outputFormat": "The shortest clear-path length (number of cells), or -1.",
    "tests": [
      {
        "input": "2\n00\n00\n",
        "expected": "2\n",
        "sample": true
      },
      {
        "input": "3\n000\n110\n110\n",
        "expected": "4\n",
        "sample": true
      },
      {
        "input": "3\n000\n111\n000\n",
        "expected": "-1\n",
        "sample": false
      },
      {
        "input": "1\n0\n",
        "expected": "1\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split('\\n')\n    n = int(data[0].strip())\n    grid = [data[1+i].strip() for i in range(n)]\n    # TODO: print the shortest clear-path length, or -1\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<string> g(n);\n    for (auto& s : g) cin >> s;\n    // TODO: print the shortest clear-path length, or -1\n    return 0;\n}\n"
    }
  },
  {
    "id": "image-smoother",
    "title": "Image Smoother",
    "diff": "Easy",
    "pattern": "Matrix / Convolution",
    "week": 3,
    "statement": "<p>For each cell output the floor of the average of itself and its (up to 8) neighbors \u2014 a 3\u00d73 box filter.</p>",
    "inputFormat": "Line 1: rows cols. Next rows lines: cols integers each.",
    "outputFormat": "The smoothed matrix, rows lines of cols integers.",
    "tests": [
      {
        "input": "3 3\n1 1 1\n1 0 1\n1 1 1\n",
        "expected": "0 0 0\n0 0 0\n0 0 0\n",
        "sample": true
      },
      {
        "input": "2 2\n100 200\n100 200\n",
        "expected": "150 150\n150 150\n",
        "sample": true
      },
      {
        "input": "1 3\n2 4 6\n",
        "expected": "3 4 5\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    rows = int(data[0]); cols = int(data[1])\n    vals = list(map(int, data[2:2+rows*cols]))\n    m = [vals[i*cols:(i+1)*cols] for i in range(rows)]\n    # TODO: print the smoothed matrix\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int rows, cols; cin >> rows >> cols;\n    vector<vector<int>> m(rows, vector<int>(cols));\n    for (auto& r : m) for (auto& x : r) cin >> x;\n    // TODO: print the smoothed matrix\n    return 0;\n}\n"
    }
  },
  {
    "id": "k-closest-points",
    "title": "K Closest Points to Origin",
    "diff": "Medium",
    "pattern": "Heap / Sorting",
    "week": 4,
    "statement": "<p>Return the k points closest to the origin (Euclidean). Break ties by x then y so the answer is deterministic; print sorted by (distance, x, y).</p>",
    "inputFormat": "Line 1: n. Next n lines: x y. Last line: k.",
    "outputFormat": "k lines, each 'x y', ordered by distance then x then y.",
    "tests": [
      {
        "input": "3\n1 3\n-2 2\n5 8\n2\n",
        "expected": "-2 2\n1 3\n",
        "sample": true
      },
      {
        "input": "2\n3 3\n5 -1\n1\n",
        "expected": "3 3\n",
        "sample": true
      },
      {
        "input": "4\n0 1\n1 0\n2 2\n-1 -1\n3\n",
        "expected": "0 1\n1 0\n-1 -1\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    pts = []\n    idx = 1\n    for _ in range(n):\n        pts.append((int(data[idx]), int(data[idx+1]))); idx += 2\n    k = int(data[idx])\n    # TODO: print the k closest points\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<pair<int,int>> p(n);\n    for (auto& q : p) cin >> q.first >> q.second;\n    int k; cin >> k;\n    // TODO: print the k closest points\n    return 0;\n}\n"
    }
  },
  {
    "id": "max-points-on-a-line",
    "title": "Max Points on a Line",
    "diff": "Hard",
    "pattern": "Geometry",
    "week": 4,
    "statement": "<p>Given n points on a plane, return the maximum number of points that lie on the same straight line.</p>",
    "inputFormat": "Line 1: n. Next n lines: x y.",
    "outputFormat": "The maximum number of collinear points.",
    "tests": [
      {
        "input": "6\n1 1\n2 2\n3 3\n1 4\n2 5\n3 6\n",
        "expected": "3\n",
        "sample": true
      },
      {
        "input": "3\n1 1\n3 2\n5 3\n",
        "expected": "3\n",
        "sample": true
      },
      {
        "input": "1\n0 0\n",
        "expected": "1\n",
        "sample": false
      },
      {
        "input": "4\n0 0\n1 1\n2 2\n3 3\n",
        "expected": "4\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    pts = []\n    idx = 1\n    for _ in range(n):\n        pts.append((int(data[idx]), int(data[idx+1]))); idx += 2\n    # TODO: print max points on a line\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<pair<int,int>> p(n);\n    for (auto& q : p) cin >> q.first >> q.second;\n    // TODO: print max points on a line\n    return 0;\n}\n"
    }
  },
  {
    "id": "moving-average",
    "title": "Moving Average from Data Stream",
    "diff": "Easy",
    "pattern": "Stream / Sliding Window",
    "week": 5,
    "statement": "<p>Maintain a moving average over a sliding window of the given size. For each incoming value, print the current average (5 decimals).</p>",
    "inputFormat": "Line 1: window size. Line 2: m (count). Line 3: m integers (the stream).",
    "outputFormat": "m lines, each the moving average formatted to 5 decimals.",
    "tests": [
      {
        "input": "3\n5\n1 10 3 5 20\n",
        "expected": "1.00000\n5.50000\n4.66667\n6.00000\n9.33333\n",
        "sample": true
      },
      {
        "input": "1\n3\n4 0 8\n",
        "expected": "4.00000\n0.00000\n8.00000\n",
        "sample": true
      },
      {
        "input": "2\n4\n2 2 2 2\n",
        "expected": "2.00000\n2.00000\n2.00000\n2.00000\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    size = int(data[0]); m = int(data[1])\n    vals = list(map(int, data[2:2+m]))\n    # TODO: print each moving average with '%.5f' % avg\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int size, m; cin >> size >> m;\n    vector<int> v(m);\n    for (auto& x : v) cin >> x;\n    cout << fixed << setprecision(5);\n    // TODO: print each moving average\n    return 0;\n}\n"
    }
  },
  {
    "id": "sliding-window-maximum",
    "title": "Sliding Window Maximum",
    "diff": "Hard",
    "pattern": "Monotonic Deque",
    "week": 5,
    "statement": "<p>Given an array and window size k, output the maximum of each contiguous window.</p>",
    "inputFormat": "Line 1: n. Line 2: n integers. Line 3: k.",
    "outputFormat": "The window maxima, space-separated.",
    "tests": [
      {
        "input": "8\n1 3 -1 -3 5 3 6 7\n3\n",
        "expected": "3 3 5 5 6 7\n",
        "sample": true
      },
      {
        "input": "1\n1\n1\n",
        "expected": "1\n",
        "sample": true
      },
      {
        "input": "6\n9 8 7 6 5 4\n2\n",
        "expected": "9 8 7 6 5\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    a = list(map(int, data[1:1+n]))\n    k = int(data[1+n])\n    # TODO: print the window maxima\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<int> a(n);\n    for (auto& x : a) cin >> x;\n    int k; cin >> k;\n    // TODO: print the window maxima\n    return 0;\n}\n"
    }
  },
  {
    "id": "course-schedule",
    "title": "Course Schedule",
    "diff": "Medium",
    "pattern": "Graph / Topo Sort",
    "week": 6,
    "statement": "<p>There are numCourses courses. Each edge 'a b' means course a depends on course b. Determine if all courses can be finished (no cycle).</p>",
    "inputFormat": "Line 1: numCourses. Line 2: e (edges). Next e lines: a b.",
    "outputFormat": "'true' or 'false'.",
    "tests": [
      {
        "input": "2\n1\n1 0\n",
        "expected": "true\n",
        "sample": true
      },
      {
        "input": "2\n2\n1 0\n0 1\n",
        "expected": "false\n",
        "sample": true
      },
      {
        "input": "4\n3\n1 0\n2 1\n3 2\n",
        "expected": "true\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0]); e = int(data[1])\n    edges = []\n    idx = 2\n    for _ in range(e):\n        edges.append((int(data[idx]), int(data[idx+1]))); idx += 2\n    # TODO: print 'true' or 'false'\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n, e; cin >> n >> e;\n    vector<pair<int,int>> edges(e);\n    for (auto& p : edges) cin >> p.first >> p.second;\n    // TODO: print \"true\" or \"false\"\n    return 0;\n}\n"
    }
  },
  {
    "id": "network-delay-time",
    "title": "Network Delay Time",
    "diff": "Medium",
    "pattern": "Dijkstra",
    "week": 6,
    "statement": "<p>A signal starts at node k in a network of n nodes (1-indexed). Each directed edge 'u v w' has travel time w. Return the time for all nodes to receive the signal, or -1 if impossible.</p>",
    "inputFormat": "Line 1: n m k. Next m lines: u v w.",
    "outputFormat": "The delay time, or -1.",
    "tests": [
      {
        "input": "4 4 2\n2 1 1\n2 3 1\n3 4 1\n1 4 5\n",
        "expected": "2\n",
        "sample": true
      },
      {
        "input": "2 1 1\n1 2 1\n",
        "expected": "1\n",
        "sample": true
      },
      {
        "input": "2 1 2\n1 2 1\n",
        "expected": "-1\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0]); m = int(data[1]); k = int(data[2])\n    edges = []\n    idx = 3\n    for _ in range(m):\n        edges.append((int(data[idx]), int(data[idx+1]), int(data[idx+2]))); idx += 3\n    # TODO: print the delay time or -1\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n, m, k; cin >> n >> m >> k;\n    vector<array<int,3>> edges(m);\n    for (auto& e : edges) cin >> e[0] >> e[1] >> e[2];\n    // TODO: print the delay time or -1\n    return 0;\n}\n"
    }
  },
  {
    "id": "maximal-square",
    "title": "Maximal Square",
    "diff": "Medium",
    "pattern": "DP / Grid",
    "week": 7,
    "statement": "<p>In a binary grid, find the largest square containing only 1s and return its <b>area</b>.</p>",
    "inputFormat": "Line 1: rows cols. Next rows lines: a string of cols characters ('0'/'1').",
    "outputFormat": "The area of the largest all-ones square.",
    "tests": [
      {
        "input": "4 5\n10100\n10111\n11111\n10010\n",
        "expected": "4\n",
        "sample": true
      },
      {
        "input": "2 2\n01\n10\n",
        "expected": "1\n",
        "sample": true
      },
      {
        "input": "1 1\n0\n",
        "expected": "0\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split('\\n')\n    rows, cols = map(int, data[0].split())\n    grid = [data[1+i].strip() for i in range(rows)]\n    # TODO: print the maximal square area\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int rows, cols; cin >> rows >> cols;\n    vector<string> g(rows);\n    for (auto& s : g) cin >> s;\n    // TODO: print the maximal square area\n    return 0;\n}\n"
    }
  },
  {
    "id": "word-ladder",
    "title": "Word Ladder",
    "diff": "Hard",
    "pattern": "BFS",
    "week": 7,
    "statement": "<p>Return the number of words in the shortest transformation sequence from beginWord to endWord, changing one letter at a time, where each intermediate word must be in the word list. Return 0 if impossible. (Length counts both endpoints.)</p>",
    "inputFormat": "Line 1: beginWord. Line 2: endWord. Line 3: count. Next count lines: the word list.",
    "outputFormat": "The length of the shortest sequence, or 0.",
    "tests": [
      {
        "input": "hit\ncog\n6\nhot\ndot\ndog\nlot\nlog\ncog\n",
        "expected": "5\n",
        "sample": true
      },
      {
        "input": "hit\ncog\n5\nhot\ndot\ndog\nlot\nlog\n",
        "expected": "0\n",
        "sample": true
      },
      {
        "input": "a\nc\n2\nb\nc\n",
        "expected": "2\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    lines = sys.stdin.read().split('\\n')\n    begin = lines[0].strip(); end = lines[1].strip()\n    cnt = int(lines[2])\n    words = [lines[3+i].strip() for i in range(cnt)]\n    # TODO: print shortest ladder length or 0\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    string begin, end; cin >> begin >> end;\n    int cnt; cin >> cnt;\n    vector<string> words(cnt);\n    for (auto& w : words) cin >> w;\n    // TODO: print shortest ladder length or 0\n    return 0;\n}\n"
    }
  },
  {
    "id": "merge-intervals",
    "title": "Merge Intervals",
    "diff": "Medium",
    "pattern": "Intervals",
    "week": 8,
    "statement": "<p>Merge all overlapping intervals and print them sorted by start.</p>",
    "inputFormat": "Line 1: n. Next n lines: start end.",
    "outputFormat": "The merged intervals, one 'start end' per line, sorted by start.",
    "tests": [
      {
        "input": "4\n1 3\n2 6\n8 10\n15 18\n",
        "expected": "1 6\n8 10\n15 18\n",
        "sample": true
      },
      {
        "input": "2\n1 4\n4 5\n",
        "expected": "1 5\n",
        "sample": true
      },
      {
        "input": "3\n1 4\n0 4\n2 3\n",
        "expected": "0 4\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    iv = []\n    idx = 1\n    for _ in range(n):\n        iv.append((int(data[idx]), int(data[idx+1]))); idx += 2\n    # TODO: print merged intervals\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<pair<int,int>> iv(n);\n    for (auto& p : iv) cin >> p.first >> p.second;\n    // TODO: print merged intervals\n    return 0;\n}\n"
    }
  },
  {
    "id": "set-matrix-zeroes",
    "title": "Set Matrix Zeroes",
    "diff": "Medium",
    "pattern": "Matrix",
    "week": 2,
    "statement": "<p>If an element is 0, set its entire row and column to 0 \u2014 and print the result. (Classic follow-up: do it in O(1) extra space.)</p>",
    "inputFormat": "Line 1: rows cols. Next rows lines: cols integers each.",
    "outputFormat": "The modified matrix, rows lines of cols integers.",
    "tests": [
      {
        "input": "3 3\n1 1 1\n1 0 1\n1 1 1\n",
        "expected": "1 0 1\n0 0 0\n1 0 1\n",
        "sample": true
      },
      {
        "input": "3 4\n0 1 2 0\n3 4 5 2\n1 3 1 5\n",
        "expected": "0 0 0 0\n0 4 5 0\n0 3 1 0\n",
        "sample": true
      },
      {
        "input": "1 1\n5\n",
        "expected": "5\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    rows = int(data[0]); cols = int(data[1])\n    vals = list(map(int, data[2:2+rows*cols]))\n    m = [vals[i*cols:(i+1)*cols] for i in range(rows)]\n    # TODO: zero out rows/cols and print the matrix\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int rows, cols; cin >> rows >> cols;\n    vector<vector<int>> m(rows, vector<int>(cols));\n    for (auto& r : m) for (auto& x : r) cin >> x;\n    // TODO: zero out rows/cols and print the matrix\n    return 0;\n}\n"
    }
  },
  {
    "id": "pacific-atlantic",
    "title": "Pacific Atlantic Water Flow",
    "diff": "Medium",
    "pattern": "Grid DFS/BFS",
    "week": 3,
    "statement": "<p>Water flows from a cell to a 4-neighbor with height <b>less than or equal</b> to it. The Pacific touches the top and left edges; the Atlantic touches the bottom and right edges. Print all cells from which water can reach <b>both</b> oceans.</p>",
    "inputFormat": "Line 1: m n. Next m lines: n integers (heights).",
    "outputFormat": "Each qualifying cell as 'row col' (0-indexed), one per line, sorted by row then col.",
    "tests": [
      {
        "input": "5 5\n1 2 2 3 5\n3 2 3 4 4\n2 4 5 3 1\n6 7 1 4 5\n5 1 1 2 4\n",
        "expected": "0 4\n1 3\n1 4\n2 2\n3 0\n3 1\n4 0\n",
        "sample": true
      },
      {
        "input": "1 1\n1\n",
        "expected": "0 0\n",
        "sample": true
      },
      {
        "input": "3 3\n1 2 3\n8 9 4\n7 6 5\n",
        "expected": "0 2\n1 0\n1 1\n1 2\n2 0\n2 1\n2 2\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    m = int(data[0]); n = int(data[1])\n    vals = list(map(int, data[2:2+m*n]))\n    h = [vals[i*n:(i+1)*n] for i in range(m)]\n    # TODO: print cells (row col) that reach both oceans, sorted\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int m, n; cin >> m >> n;\n    vector<vector<int>> h(m, vector<int>(n));\n    for (auto& r : h) for (auto& x : r) cin >> x;\n    // TODO: print cells (row col) that reach both oceans, sorted\n    return 0;\n}\n"
    }
  },
  {
    "id": "find-k-closest-elements",
    "title": "Find K Closest Elements",
    "diff": "Medium",
    "pattern": "Binary Search",
    "week": 4,
    "statement": "<p>Given a <b>sorted</b> array, return the k elements closest to x, in ascending order. Closeness is |a-x|; ties prefer the smaller value.</p>",
    "inputFormat": "Line 1: n. Line 2: n integers (ascending). Line 3: k x.",
    "outputFormat": "The k closest elements, ascending, space-separated.",
    "tests": [
      {
        "input": "5\n1 2 3 4 5\n4 3\n",
        "expected": "1 2 3 4\n",
        "sample": true
      },
      {
        "input": "5\n1 2 3 4 5\n4 -1\n",
        "expected": "1 2 3 4\n",
        "sample": true
      },
      {
        "input": "6\n1 1 1 10 10 10\n1 9\n",
        "expected": "10\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    a = list(map(int, data[1:1+n]))\n    k = int(data[1+n]); x = int(data[2+n])\n    # TODO: print the k closest elements (ascending)\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n; vector<int> a(n);\n    for (auto& v : a) cin >> v;\n    int k, x; cin >> k >> x;\n    // TODO: print the k closest elements (ascending)\n    return 0;\n}\n"
    }
  },
  {
    "id": "find-median-from-data-stream",
    "title": "Find Median from Data Stream",
    "diff": "Hard",
    "pattern": "Two Heaps",
    "week": 5,
    "statement": "<p>Process a stream of operations. <code>add x</code> inserts a number; <code>median</code> queries the current median. For each <code>median</code>, print the median formatted to <b>one decimal</b> (e.g. <code>2.0</code>, <code>2.5</code>).</p>",
    "inputFormat": "Line 1: q (operations). Next q lines: 'add x' or 'median'.",
    "outputFormat": "One line per 'median' query: the median to 1 decimal.",
    "tests": [
      {
        "input": "5\nadd 1\nadd 2\nmedian\nadd 3\nmedian\n",
        "expected": "1.5\n2.0\n",
        "sample": true
      },
      {
        "input": "4\nadd 5\nmedian\nadd 1\nmedian\n",
        "expected": "5.0\n3.0\n",
        "sample": true
      },
      {
        "input": "3\nadd 2\nadd 2\nmedian\n",
        "expected": "2.0\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    idx = 0\n    q = int(data[idx]); idx += 1\n    out = []\n    # TODO: maintain a structure (e.g. two heaps)\n    for _ in range(q):\n        cmd = data[idx]; idx += 1\n        if cmd == \"add\":\n            x = int(data[idx]); idx += 1\n            pass  # TODO: add x\n        else:\n            pass  # TODO: out.append('%.1f' % median)\n    print(\"\\n\".join(out))\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int q; cin >> q;\n    cout << fixed << setprecision(1);\n    string cmd;\n    // TODO: maintain a structure (e.g. two heaps)\n    for (int i = 0; i < q; i++) {\n        cin >> cmd;\n        if (cmd == \"add\") { long long x; cin >> x; /* TODO */ }\n        else { /* TODO: print median */ }\n    }\n    return 0;\n}\n"
    }
  },
  {
    "id": "graph-valid-tree",
    "title": "Graph Valid Tree",
    "diff": "Medium",
    "pattern": "Union-Find",
    "week": 6,
    "statement": "<p>Given n nodes (0..n-1) and an undirected edge list, decide whether the graph forms a <b>valid tree</b> (fully connected and acyclic).</p>",
    "inputFormat": "Line 1: n m. Next m lines: u v.",
    "outputFormat": "'true' or 'false'.",
    "tests": [
      {
        "input": "5\n4\n0 1\n0 2\n0 3\n1 4\n",
        "expected": "true\n",
        "sample": true
      },
      {
        "input": "5\n5\n0 1\n1 2\n2 3\n1 3\n1 4\n",
        "expected": "false\n",
        "sample": true
      },
      {
        "input": "4\n2\n0 1\n2 3\n",
        "expected": "false\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0]); m = int(data[1])\n    edges = []\n    idx = 2\n    for _ in range(m):\n        edges.append((int(data[idx]), int(data[idx+1]))); idx += 2\n    # TODO: print 'true' if it is a valid tree else 'false'\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n, m; cin >> n >> m;\n    vector<pair<int,int>> edges(m);\n    for (auto& e : edges) cin >> e.first >> e.second;\n    // TODO: print \"true\" or \"false\"\n    return 0;\n}\n"
    }
  },
  {
    "id": "lru-cache",
    "title": "LRU Cache",
    "diff": "Medium",
    "pattern": "Design / Hash + List",
    "week": 7,
    "statement": "<p>Implement an LRU cache with the given capacity. <code>put k v</code> inserts/updates; <code>get k</code> returns the value or -1 and marks it most-recently-used. Evict the least-recently-used item when over capacity. Print the result of every <code>get</code>.</p>",
    "inputFormat": "Line 1: capacity. Line 2: q. Next q lines: 'put k v' or 'get k'.",
    "outputFormat": "One line per 'get': the value, or -1.",
    "tests": [
      {
        "input": "2\n6\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 2\nget 3\n",
        "expected": "1\n-1\n3\n",
        "sample": true
      },
      {
        "input": "1\n4\nput 1 10\nget 1\nput 2 20\nget 1\n",
        "expected": "10\n-1\n",
        "sample": true
      },
      {
        "input": "2\n3\nget 5\nput 5 5\nget 5\n",
        "expected": "-1\n5\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    idx = 0\n    cap = int(data[idx]); idx += 1\n    q = int(data[idx]); idx += 1\n    out = []\n    # TODO: build the LRU cache (capacity = cap)\n    for _ in range(q):\n        cmd = data[idx]; idx += 1\n        if cmd == \"put\":\n            k = int(data[idx]); v = int(data[idx+1]); idx += 2\n            pass  # TODO: put k, v\n        else:\n            k = int(data[idx]); idx += 1\n            pass  # TODO: out.append(str(get(k)))\n    print(\"\\n\".join(out))\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int cap, q; cin >> cap >> q;\n    string cmd;\n    // TODO: build the LRU cache (capacity = cap)\n    for (int i = 0; i < q; i++) {\n        cin >> cmd;\n        if (cmd == \"put\") { int k, v; cin >> k >> v; /* TODO */ }\n        else { int k; cin >> k; /* TODO: print get(k) */ }\n    }\n    return 0;\n}\n"
    }
  },
  {
    "id": "design-circular-queue",
    "title": "Design Circular Queue",
    "diff": "Medium",
    "pattern": "Design / Ring Buffer",
    "week": 8,
    "statement": "<p>Implement a circular queue of capacity k. Operations: <code>enQueue x</code>, <code>deQueue</code>, <code>Front</code>, <code>Rear</code>, <code>isEmpty</code>, <code>isFull</code>. enQueue/deQueue print <code>true</code>/<code>false</code>; Front/Rear print the value or -1; isEmpty/isFull print <code>true</code>/<code>false</code>. Print the result of every operation.</p>",
    "inputFormat": "Line 1: k (capacity). Line 2: q. Next q lines: an operation (with an arg for enQueue).",
    "outputFormat": "One line per operation: its return value.",
    "tests": [
      {
        "input": "3\n7\nenQueue 1\nenQueue 2\nenQueue 3\nenQueue 4\nRear\nisFull\ndeQueue\n",
        "expected": "true\ntrue\ntrue\nfalse\n3\ntrue\ntrue\n",
        "sample": true
      },
      {
        "input": "2\n4\nisEmpty\nenQueue 5\nFront\ndeQueue\n",
        "expected": "true\ntrue\n5\ntrue\n",
        "sample": true
      },
      {
        "input": "1\n3\nenQueue 9\nRear\ndeQueue\n",
        "expected": "true\n9\ntrue\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    idx = 0\n    k = int(data[idx]); idx += 1\n    q = int(data[idx]); idx += 1\n    out = []\n    # TODO: build the circular queue (capacity = k)\n    for _ in range(q):\n        cmd = data[idx]; idx += 1\n        if cmd == \"enQueue\":\n            x = int(data[idx]); idx += 1\n            pass  # TODO: out.append('true'/'false')\n        else:\n            pass  # TODO: handle deQueue/Front/Rear/isEmpty/isFull\n    print(\"\\n\".join(out))\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int k, q; cin >> k >> q;\n    string cmd;\n    // TODO: build the circular queue (capacity = k)\n    for (int i = 0; i < q; i++) {\n        cin >> cmd;\n        if (cmd == \"enQueue\") { int x; cin >> x; /* TODO */ }\n        else { /* TODO: deQueue/Front/Rear/isEmpty/isFull */ }\n    }\n    return 0;\n}\n"
    }
  },
  {
    "id": "time-based-key-value-store",
    "title": "Time-Based Key-Value Store",
    "diff": "Medium",
    "pattern": "Design / Binary Search",
    "week": 8,
    "statement": "<p>Implement a store where <code>set key value ts</code> stores a value at timestamp ts (timestamps strictly increase per key), and <code>get key ts</code> returns the value with the largest timestamp \u2264 ts, or an empty string if none. Print every <code>get</code> result.</p>",
    "inputFormat": "Line 1: q. Next q lines: 'set key value ts' or 'get key ts'. (key/value are single tokens.)",
    "outputFormat": "One line per 'get': the value, or an empty line if none.",
    "tests": [
      {
        "input": "5\nset foo bar 1\nget foo 1\nget foo 3\nset foo baz 4\nget foo 4\n",
        "expected": "bar\nbar\nbaz\n",
        "sample": true
      },
      {
        "input": "3\nget x 1\nset x a 5\nget x 10\n",
        "expected": "\na\n",
        "sample": true
      },
      {
        "input": "4\nset k v1 1\nset k v2 2\nget k 1\nget k 2\n",
        "expected": "v1\nv2\n",
        "sample": false
      }
    ],
    "category": "leetcode",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    idx = 0\n    q = int(data[idx]); idx += 1\n    out = []\n    # TODO: build the time-based store\n    for _ in range(q):\n        cmd = data[idx]; idx += 1\n        if cmd == \"set\":\n            key = data[idx]; val = data[idx+1]; ts = int(data[idx+2]); idx += 3\n            pass  # TODO: set\n        else:\n            key = data[idx]; ts = int(data[idx+1]); idx += 2\n            pass  # TODO: out.append(get(key, ts))\n    print(\"\\n\".join(out))\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int q; cin >> q;\n    string cmd;\n    // TODO: build the time-based store\n    for (int i = 0; i < q; i++) {\n        cin >> cmd;\n        if (cmd == \"set\") { string key, val; int ts; cin >> key >> val >> ts; /* TODO */ }\n        else { string key; int ts; cin >> key >> ts; /* TODO: print get */ }\n    }\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-least-squares-line",
    "title": "Least-Squares Line Fit",
    "diff": "Easy",
    "pattern": "Linear Algebra",
    "week": 1,
    "statement": "<p>Fit the best line <code>y = m\u00b7x + b</code> to noisy points by ordinary least squares (closed-form normal equations). Print the slope and intercept.</p>",
    "inputFormat": "Line 1: n. Next n lines: x y (floats).",
    "outputFormat": "'m b' (slope, intercept) to ~4 decimals.",
    "tests": [
      {
        "input": "4\n0 1\n1 3\n2 5\n3 7\n",
        "expected": "2.0000 1.0000\n",
        "sample": true
      },
      {
        "input": "5\n0 1.1\n1 0.9\n2 3.2\n3 2.8\n4 5.1\n",
        "expected": "0.9900 0.6400\n",
        "sample": true
      },
      {
        "input": "3\n1 2\n2 4\n3 6\n",
        "expected": "2.0000 0.0000\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "float",
    "tol": 0.001,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    pts = [(float(data[1+2*i]), float(data[2+2*i])) for i in range(n)]\n    # TODO: print 'm b' via least squares\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    cout << fixed << setprecision(6);\n    int n; cin >> n;\n    vector<double> x(n), y(n);\n    for (int i = 0; i < n; i++) cin >> x[i] >> y[i];\n    // TODO: print 'm b' via least squares\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-covariance-mahalanobis",
    "title": "Covariance & Mahalanobis Distance",
    "diff": "Medium",
    "pattern": "Probability",
    "week": 1,
    "statement": "<p>From a set of 2D points compute the (sample, divided by n-1) covariance matrix, then the Mahalanobis distance of a query point to the mean.</p>",
    "inputFormat": "Line 1: n. Next n lines: x y. Last line: qx qy (the query point).",
    "outputFormat": "Line 1: covariance 'c00 c01 c10 c11'. Line 2: Mahalanobis distance.",
    "tests": [
      {
        "input": "4\n0 0\n2 0\n0 2\n2 2\n3 3\n",
        "expected": "1.3333 0.0000 0.0000 1.3333\n2.4495\n",
        "sample": true
      },
      {
        "input": "5\n1 2\n2 1\n3 5\n4 3\n5 6\n3 4\n",
        "expected": "2.5000 2.5000 2.5000 4.3000\n0.4472\n",
        "sample": true
      },
      {
        "input": "3\n0 0\n2 1\n1 3\n4 4\n",
        "expected": "1.0000 0.5000 0.5000 2.3333\n3.1070\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "float",
    "tol": 0.001,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    pts = [(float(data[1+2*i]), float(data[2+2*i])) for i in range(n)]\n    qx = float(data[1+2*n]); qy = float(data[2+2*n])\n    # TODO: print covariance (4 nums) then Mahalanobis distance\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    cout << fixed << setprecision(6);\n    int n; cin >> n;\n    vector<double> x(n), y(n);\n    for (int i = 0; i < n; i++) cin >> x[i] >> y[i];\n    double qx, qy; cin >> qx >> qy;\n    // TODO: print covariance then Mahalanobis distance\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-quaternion-rotate",
    "title": "Rotate a Vector by a Quaternion",
    "diff": "Easy",
    "pattern": "3D Geometry",
    "week": 2,
    "statement": "<p>Given a (possibly unnormalized) quaternion [w x y z] and a 3D vector, return the rotated vector. Normalize the quaternion first.</p>",
    "inputFormat": "Line 1: w x y z. Line 2: vx vy vz.",
    "outputFormat": "The rotated vector 'rx ry rz'.",
    "tests": [
      {
        "input": "0.7071068 0 0 0.7071068\n1 0 0\n",
        "expected": "-0.0000 1.0000 0.0000\n",
        "sample": true
      },
      {
        "input": "1 0 0 0\n3 -2 5\n",
        "expected": "3.0000 -2.0000 5.0000\n",
        "sample": true
      },
      {
        "input": "0.5 0.5 0.5 0.5\n1 0 0\n",
        "expected": "0.0000 1.0000 0.0000\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "float",
    "tol": 0.001,
    "starter": {
      "python": "import sys\n\ndef main():\n    d = list(map(float, sys.stdin.read().split()))\n    w, x, y, z = d[0:4]\n    vx, vy, vz = d[4:7]\n    # TODO: normalize q and print the rotated vector\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    cout << fixed << setprecision(6);\n    double w, x, y, z, vx, vy, vz;\n    cin >> w >> x >> y >> z >> vx >> vy >> vz;\n    // TODO: normalize q and print the rotated vector\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-transform-point",
    "title": "Compose SE(3) and Transform a Point",
    "diff": "Medium",
    "pattern": "3D Geometry",
    "week": 2,
    "statement": "<p>Given two rigid transforms T1=(R1,t1) and T2=(R2,t2) (rotations are 3\u00d73 row-major), apply the composition <code>T1 \u2218 T2</code> to a point p, i.e. compute <code>R1\u00b7(R2\u00b7p + t2) + t1</code>.</p>",
    "inputFormat": "Line 1: R1 (9 numbers, row-major). Line 2: t1 (3). Line 3: R2 (9). Line 4: t2 (3). Line 5: p (3).",
    "outputFormat": "The transformed point 'x y z'.",
    "tests": [
      {
        "input": "1 0 0 0 1 0 0 0 1\n5 2 0\n0 -1 0 1 0 0 0 0 1\n0 0 0\n1 0 0\n",
        "expected": "5.0000 3.0000 0.0000\n",
        "sample": true
      },
      {
        "input": "1 0 0 0 1 0 0 0 1\n0 0 0\n1 0 0 0 1 0 0 0 1\n1 2 3\n0 0 0\n",
        "expected": "1.0000 2.0000 3.0000\n",
        "sample": true
      },
      {
        "input": "0 -1 0 1 0 0 0 0 1\n1 1 1\n1 0 0 0 1 0 0 0 1\n0 0 0\n2 0 0\n",
        "expected": "1.0000 3.0000 1.0000\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "float",
    "tol": 0.001,
    "starter": {
      "python": "import sys\n\ndef main():\n    d = list(map(float, sys.stdin.read().split()))\n    R1 = d[0:9]; t1 = d[9:12]; R2 = d[12:21]; t2 = d[21:24]; p = d[24:27]\n    # TODO: print R1*(R2*p + t2) + t1\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    cout << fixed << setprecision(6);\n    vector<double> d(27);\n    for (auto& v : d) cin >> v;\n    // d[0:9]=R1, d[9:12]=t1, d[12:21]=R2, d[21:24]=t2, d[24:27]=p\n    // TODO: print R1*(R2*p + t2) + t1\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-convolution-2d",
    "title": "2D Cross-Correlation",
    "diff": "Easy",
    "pattern": "Image Processing",
    "week": 3,
    "statement": "<p>Apply a 3\u00d73 kernel to an image by <b>cross-correlation</b> (slide the kernel as-is, no flip) with zero padding. Output the result (same size). Integer arithmetic \u2014 e.g. feed a Sobel kernel to get edges.</p>",
    "inputFormat": "Line 1: H W. Next H lines: W integers (image). Next 3 lines: 3 integers each (kernel).",
    "outputFormat": "The H\u00d7W result, integers.",
    "tests": [
      {
        "input": "3 3\n0 0 0\n0 1 0\n0 0 0\n1 2 1\n2 4 2\n1 2 1\n",
        "expected": "1 2 1\n2 4 2\n1 2 1\n",
        "sample": true
      },
      {
        "input": "3 4\n10 10 10 10\n10 10 10 10\n10 10 10 10\n-1 0 1\n-2 0 2\n-1 0 1\n",
        "expected": "30 0 0 -30\n40 0 0 -40\n30 0 0 -30\n",
        "sample": true
      },
      {
        "input": "1 3\n1 2 3\n0 0 0\n0 1 0\n0 0 0\n",
        "expected": "1 2 3\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    H = int(data[0]); W = int(data[1]); idx = 2\n    img = [[int(data[idx + i*W + j]) for j in range(W)] for i in range(H)]; idx += H*W\n    ker = [[int(data[idx + i*3 + j]) for j in range(3)] for i in range(3)]\n    # TODO: print the cross-correlated image (zero padding)\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int H, W; cin >> H >> W;\n    vector<vector<int>> img(H, vector<int>(W));\n    for (auto& r : img) for (auto& v : r) cin >> v;\n    vector<vector<int>> ker(3, vector<int>(3));\n    for (auto& r : ker) for (auto& v : r) cin >> v;\n    // TODO: print the cross-correlated image (zero padding)\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-project-point",
    "title": "Project a 3D Point to a Pixel",
    "diff": "Easy",
    "pattern": "Camera Model",
    "week": 3,
    "statement": "<p>Project a world point to pixel coordinates with the pinhole model: transform to the camera frame with (R,t), then apply intrinsics. <code>u = fx\u00b7X/Z + cx</code>, <code>v = fy\u00b7Y/Z + cy</code>.</p>",
    "inputFormat": "Line 1: fx fy cx cy. Line 2: R (9, row-major). Line 3: t (3). Line 4: world point (3).",
    "outputFormat": "The pixel 'u v'.",
    "tests": [
      {
        "input": "800 800 320 240\n1 0 0 0 1 0 0 0 1\n0 0 0\n0 0 5\n",
        "expected": "320.0000 240.0000\n",
        "sample": true
      },
      {
        "input": "800 800 320 240\n1 0 0 0 1 0 0 0 1\n0 0 0\n1 0.5 5\n",
        "expected": "480.0000 320.0000\n",
        "sample": true
      },
      {
        "input": "500 500 100 100\n1 0 0 0 1 0 0 0 1\n0 0 2\n1 -1 3\n",
        "expected": "200.0000 0.0000\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "float",
    "tol": 0.001,
    "starter": {
      "python": "import sys\n\ndef main():\n    d = list(map(float, sys.stdin.read().split()))\n    fx, fy, cx, cy = d[0:4]; R = d[4:13]; t = d[13:16]; X = d[16:19]\n    # TODO: print the pixel 'u v'\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    cout << fixed << setprecision(6);\n    double fx, fy, cx, cy; cin >> fx >> fy >> cx >> cy;\n    vector<double> R(9); for (auto& v : R) cin >> v;\n    vector<double> t(3); for (auto& v : t) cin >> v;\n    vector<double> X(3); for (auto& v : X) cin >> v;\n    // TODO: print the pixel 'u v'\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-ransac-line-inliers",
    "title": "RANSAC Line \u2014 Max Inliers",
    "diff": "Medium",
    "pattern": "Robust Fitting",
    "week": 4,
    "statement": "<p>Find the line (through some pair of the given points) that has the most inliers, where a point is an inlier if its perpendicular distance to the line is \u2264 threshold. Print the maximum inlier count. (Deterministic version of RANSAC's scoring \u2014 try every pair.)</p>",
    "inputFormat": "Line 1: n. Next n lines: x y. Last line: threshold (float).",
    "outputFormat": "The maximum number of inliers (an integer).",
    "tests": [
      {
        "input": "5\n0 0\n1 1\n2 2\n3 3\n0 5\n0.1\n",
        "expected": "4\n",
        "sample": true
      },
      {
        "input": "6\n0 0\n1 0\n2 0\n0 1\n1 1\n2 1\n0.1\n",
        "expected": "3\n",
        "sample": true
      },
      {
        "input": "4\n0 0\n1 1\n2 2\n5 0\n0.5\n",
        "expected": "3\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    pts = [(float(data[1+2*i]), float(data[2+2*i])) for i in range(n)]\n    thresh = float(data[1+2*n])\n    # TODO: print the max inlier count over all candidate lines\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<double> x(n), y(n);\n    for (int i = 0; i < n; i++) cin >> x[i] >> y[i];\n    double thresh; cin >> thresh;\n    // TODO: print the max inlier count over all candidate lines\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-rigid-align-2d",
    "title": "2D Rigid Point-Set Alignment (Kabsch)",
    "diff": "Medium",
    "pattern": "Registration",
    "week": 4,
    "statement": "<p>Given corresponding 2D point pairs (a_i \u2194 b_i), find the rotation \u03b8 and translation (tx,ty) that best maps A onto B in the least-squares sense (closed-form 2D Kabsch). Print \u03b8 (radians), tx, ty.</p>",
    "inputFormat": "Line 1: n. Next n lines: ax ay bx by.",
    "outputFormat": "'theta tx ty' (theta in radians).",
    "tests": [
      {
        "input": "3\n0 0 1 1\n1 0 1 2\n0 1 0 2\n",
        "expected": "0.9828 0.7591 1.2044\n",
        "sample": true
      },
      {
        "input": "3\n0 0 0 0\n1 0 0 1\n2 0 0 2\n",
        "expected": "1.5708 -0.0000 0.0000\n",
        "sample": true
      },
      {
        "input": "4\n0 0 5 5\n1 0 6 5\n1 1 6 6\n0 1 5 6\n",
        "expected": "0.0000 5.0000 5.0000\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "float",
    "tol": 0.001,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    A = [(float(data[1+4*i]), float(data[2+4*i])) for i in range(n)]\n    B = [(float(data[3+4*i]), float(data[4+4*i])) for i in range(n)]\n    # TODO: print 'theta tx ty' (2D Kabsch)\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    cout << fixed << setprecision(6);\n    int n; cin >> n;\n    vector<double> ax(n), ay(n), bx(n), by(n);\n    for (int i = 0; i < n; i++) cin >> ax[i] >> ay[i] >> bx[i] >> by[i];\n    // TODO: print 'theta tx ty' (2D Kabsch)\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-kalman-1d",
    "title": "1D Kalman Filter (scalar)",
    "diff": "Medium",
    "pattern": "State Estimation",
    "week": 5,
    "statement": "<p>Filter a noisy 1D signal with a scalar (random-walk) Kalman filter. Use <b>x\u2080 = 0, P\u2080 = 1</b>; per step: predict <code>P += q</code>; update <code>K = P/(P+r)</code>, <code>x += K\u00b7(z\u2212x)</code>, <code>P = (1\u2212K)\u00b7P</code>. Print the estimate after each measurement.</p>",
    "inputFormat": "Line 1: q r (process var, measurement var). Line 2: n. Line 3: n measurements.",
    "outputFormat": "n lines: the filtered estimate after each measurement.",
    "tests": [
      {
        "input": "0.01 1.0\n5\n1 1 1 1 1\n",
        "expected": "0.5025\n0.6711\n0.7561\n0.8078\n0.8427\n",
        "sample": true
      },
      {
        "input": "0.5 0.5\n4\n0 10 0 10\n",
        "expected": "0.0000\n6.3636\n2.4138\n7.1053\n",
        "sample": true
      },
      {
        "input": "0.1 2.0\n3\n5 5 5\n",
        "expected": "1.7742\n2.7038\n3.2841\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "float",
    "tol": 0.001,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    q = float(data[0]); r = float(data[1]); n = int(data[2])\n    z = list(map(float, data[3:3+n]))\n    # TODO: run the scalar Kalman filter; print each estimate\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    cout << fixed << setprecision(6);\n    double q, r; int n; cin >> q >> r >> n;\n    vector<double> z(n); for (auto& v : z) cin >> v;\n    // TODO: run the scalar Kalman filter; print each estimate\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-measurement-fusion",
    "title": "Inverse-Variance Sensor Fusion",
    "diff": "Easy",
    "pattern": "Sensor Fusion",
    "week": 5,
    "statement": "<p>Fuse N independent Gaussian measurements of the same quantity into one estimate by inverse-variance weighting: <code>1/\u03c3\u00b2 = \u03a3 1/\u03c3\u1d62\u00b2</code>, <code>\u03bc = (\u03a3 \u03bc\u1d62/\u03c3\u1d62\u00b2)\u00b7\u03c3\u00b2</code>. Print the fused mean and variance.</p>",
    "inputFormat": "Line 1: n. Next n lines: mean variance.",
    "outputFormat": "'mean variance' (fused).",
    "tests": [
      {
        "input": "2\n10 1\n12 1\n",
        "expected": "11.0000 0.5000\n",
        "sample": true
      },
      {
        "input": "3\n5 0.5\n5.5 2\n4.8 1\n",
        "expected": "5.0143 0.2857\n",
        "sample": true
      },
      {
        "input": "2\n0 4\n10 1\n",
        "expected": "8.0000 0.8000\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "float",
    "tol": 0.001,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    obs = [(float(data[1+2*i]), float(data[2+2*i])) for i in range(n)]\n    # TODO: print fused 'mean variance'\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    cout << fixed << setprecision(6);\n    int n; cin >> n;\n    vector<double> m(n), v(n);\n    for (int i = 0; i < n; i++) cin >> m[i] >> v[i];\n    // TODO: print fused 'mean variance'\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-icp-2d-step",
    "title": "ICP \u2014 One Iteration (2D)",
    "diff": "Hard",
    "pattern": "SLAM / Registration",
    "week": 6,
    "statement": "<p>Perform one ICP iteration: for each source point find its nearest target point (Euclidean; ties \u2192 smallest index), then solve the best rigid transform over those correspondences (2D Kabsch). Print \u03b8, tx, ty.</p>",
    "inputFormat": "Line 1: ns. Next ns lines: x y (source). Then nt. Next nt lines: x y (target).",
    "outputFormat": "'theta tx ty' for the one-step alignment.",
    "tests": [
      {
        "input": "3\n0 0\n1 0\n0 1\n3\n5 5\n6 5\n5 6\n",
        "expected": "0.0000 4.6667 4.6667\n",
        "sample": true
      },
      {
        "input": "2\n0 0\n2 0\n3\n0 1\n1 1\n2 1\n",
        "expected": "0.0000 0.0000 1.0000\n",
        "sample": true
      },
      {
        "input": "3\n0 0\n1 1\n2 2\n3\n1 0\n2 1\n3 2\n",
        "expected": "0.0000 0.3333 -0.6667\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "float",
    "tol": 0.001,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    ns = int(data[0])\n    S = [(float(data[1+2*i]), float(data[2+2*i])) for i in range(ns)]\n    o = 1 + 2*ns\n    nt = int(data[o]); o += 1\n    T = [(float(data[o+2*i]), float(data[o+1+2*i])) for i in range(nt)]\n    # TODO: nearest-neighbor correspondences + Kabsch; print 'theta tx ty'\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    cout << fixed << setprecision(6);\n    int ns; cin >> ns;\n    vector<double> sx(ns), sy(ns);\n    for (int i = 0; i < ns; i++) cin >> sx[i] >> sy[i];\n    int nt; cin >> nt;\n    vector<double> tx(nt), ty(nt);\n    for (int i = 0; i < nt; i++) cin >> tx[i] >> ty[i];\n    // TODO: nearest-neighbor correspondences + Kabsch; print 'theta tx ty'\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-pose-graph-1d",
    "title": "1D Pose-Graph Optimization",
    "diff": "Hard",
    "pattern": "SLAM / Optimization",
    "week": 6,
    "statement": "<p>Optimize 1D poses given relative measurements. Each edge (i, j, d, w) says x_j \u2212 x_i \u2248 d with weight w. Minimize \u03a3 w\u00b7((x_j\u2212x_i)\u2212d)\u00b2 with the anchor pose fixed to 0. Print the optimized poses x\u2080\u2026x\u208d\u2099\u208b\u2081\u208e.</p>",
    "inputFormat": "Line 1: n m anchor. Next m lines: i j d w (the edges).",
    "outputFormat": "n optimized poses, space-separated.",
    "tests": [
      {
        "input": "4 4 0\n0 1 1 1\n1 2 1 1\n2 3 1 1\n0 3 3 5\n",
        "expected": "0.0000 1.0000 2.0000 3.0000\n",
        "sample": true
      },
      {
        "input": "3 2 0\n0 1 1.1 1\n1 2 0.9 1\n",
        "expected": "0.0000 1.1000 2.0000\n",
        "sample": true
      },
      {
        "input": "5 5 0\n0 1 1 1\n1 2 1 1\n2 3 1 1\n3 4 1 1\n0 4 4 10\n",
        "expected": "0.0000 1.0000 2.0000 3.0000 4.0000\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "float",
    "tol": 0.001,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0]); m = int(data[1]); anchor = int(data[2])\n    edges = [(int(data[3+4*i]), int(data[4+4*i]), float(data[5+4*i]), float(data[6+4*i])) for i in range(m)]\n    # TODO: solve the linear system (anchor fixed to 0); print the poses\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    cout << fixed << setprecision(6);\n    int n, m, anchor; cin >> n >> m >> anchor;\n    vector<array<double,4>> e(m);\n    for (auto& a : e) cin >> a[0] >> a[1] >> a[2] >> a[3];\n    // TODO: solve the linear system (anchor fixed to 0); print the poses\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-iou-nms",
    "title": "IoU + Non-Max Suppression",
    "diff": "Medium",
    "pattern": "Detection",
    "week": 7,
    "statement": "<p>Run greedy NMS on detection boxes. Sort by score descending (ties \u2192 smaller index); repeatedly keep the top box and suppress any remaining box whose IoU with it exceeds the threshold. Print the kept indices in the order kept.</p>",
    "inputFormat": "Line 1: n. Next n lines: x1 y1 x2 y2 score. Last line: iou_threshold.",
    "outputFormat": "The kept original indices, space-separated, in NMS order.",
    "tests": [
      {
        "input": "5\n10 10 50 50 0.9\n12 11 52 49 0.85\n11 9 48 51 0.8\n100 100 140 140 0.95\n102 98 138 142 0.7\n0.5\n",
        "expected": "3 0\n",
        "sample": true
      },
      {
        "input": "3\n0 0 10 10 0.5\n1 1 11 11 0.9\n20 20 30 30 0.8\n0.4\n",
        "expected": "1 2\n",
        "sample": true
      },
      {
        "input": "2\n0 0 4 4 0.6\n5 5 9 9 0.7\n0.5\n",
        "expected": "1 0\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    boxes = [tuple(map(float, data[1+5*i:5+5*i])) for i in range(n)]\n    scores = [float(data[5+5*i]) for i in range(n)]\n    thr = float(data[1+5*n])\n    # TODO: print kept indices after NMS\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<array<double,4>> b(n); vector<double> s(n);\n    for (int i = 0; i < n; i++) { cin >> b[i][0] >> b[i][1] >> b[i][2] >> b[i][3] >> s[i]; }\n    double thr; cin >> thr;\n    // TODO: print kept indices after NMS\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-average-precision",
    "title": "Average Precision (detection)",
    "diff": "Hard",
    "pattern": "Detection Metrics",
    "week": 7,
    "statement": "<p>Compute Average Precision for one class. Match detections (high score first) to ground-truth boxes by IoU \u2265 threshold (each GT once); build the precision\u2013recall curve and return the all-points AP (area under the monotonic-interpolated curve).</p>",
    "inputFormat": "Line 1: nd ng. Next nd lines: x1 y1 x2 y2 score. Next ng lines: x1 y1 x2 y2. Last line: iou_threshold.",
    "outputFormat": "The AP value.",
    "tests": [
      {
        "input": "3 2\n10 10 50 50 0.9\n100 100 140 140 0.8\n60 60 90 90 0.7\n11 9 49 51\n101 102 139 138\n0.5\n",
        "expected": "1.0000\n",
        "sample": true
      },
      {
        "input": "2 2\n0 0 10 10 0.9\n0 0 10 10 0.8\n0 0 10 10\n100 100 110 110\n0.5\n",
        "expected": "0.5000\n",
        "sample": true
      },
      {
        "input": "1 1\n0 0 10 10 0.9\n0 0 10 10\n0.5\n",
        "expected": "1.0000\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "float",
    "tol": 0.001,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    nd = int(data[0]); ng = int(data[1]); idx = 2\n    dets = []\n    for _ in range(nd):\n        dets.append((tuple(map(float, data[idx:idx+4])), float(data[idx+4]))); idx += 5\n    gts = []\n    for _ in range(ng):\n        gts.append(tuple(map(float, data[idx:idx+4]))); idx += 4\n    thr = float(data[idx])\n    # TODO: print the AP\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    cout << fixed << setprecision(6);\n    int nd, ng; cin >> nd >> ng;\n    vector<array<double,4>> det(nd); vector<double> score(nd);\n    for (int i = 0; i < nd; i++) { cin >> det[i][0] >> det[i][1] >> det[i][2] >> det[i][3] >> score[i]; }\n    vector<array<double,4>> gt(ng);\n    for (auto& g : gt) cin >> g[0] >> g[1] >> g[2] >> g[3];\n    double thr; cin >> thr;\n    // TODO: print the AP\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-ring-buffer",
    "title": "Sensor Ring Buffer",
    "diff": "Easy",
    "pattern": "Systems / Design",
    "week": 8,
    "statement": "<p>Implement a fixed-capacity ring buffer for sensor messages. <code>push x</code> appends (dropping the oldest when full); <code>latest</code> prints the most recent value (or <code>empty</code>); <code>size</code> prints the current count.</p>",
    "inputFormat": "Line 1: capacity. Line 2: q. Next q lines: 'push x', 'latest', or 'size'.",
    "outputFormat": "One line per 'latest' / 'size' query.",
    "tests": [
      {
        "input": "3\n6\npush 1\npush 2\npush 3\npush 4\nlatest\nsize\n",
        "expected": "4\n3\n",
        "sample": true
      },
      {
        "input": "2\n4\nlatest\npush 9\nsize\nlatest\n",
        "expected": "empty\n1\n9\n",
        "sample": true
      },
      {
        "input": "1\n3\npush 5\npush 6\nlatest\n",
        "expected": "6\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    idx = 0\n    cap = int(data[idx]); idx += 1\n    q = int(data[idx]); idx += 1\n    out = []\n    # TODO: maintain a ring buffer of capacity cap\n    for _ in range(q):\n        cmd = data[idx]; idx += 1\n        if cmd == \"push\":\n            x = data[idx]; idx += 1\n            pass  # TODO\n        elif cmd == \"latest\":\n            pass  # TODO: out.append(latest or 'empty')\n        else:\n            pass  # TODO: out.append(str(size))\n    print(\"\\n\".join(out))\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int cap, q; cin >> cap >> q;\n    string cmd;\n    // TODO: maintain a ring buffer of capacity cap\n    for (int i = 0; i < q; i++) {\n        cin >> cmd;\n        if (cmd == \"push\") { long long x; cin >> x; /* TODO */ }\n        else if (cmd == \"latest\") { /* TODO: print latest or 'empty' */ }\n        else { /* TODO: print size */ }\n    }\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-time-sync",
    "title": "Nearest-Timestamp Sensor Sync",
    "diff": "Medium",
    "pattern": "Systems / Sync",
    "week": 8,
    "statement": "<p>Two sensors publish timestamps (ascending). For each timestamp in stream A, find the nearest timestamp in stream B; if it's within max_dt, output the matched pair of indices. Use an O(n+m) two-pointer sweep.</p>",
    "inputFormat": "Line 1: na. Line 2: na floats (A). Line 3: nb. Line 4: nb floats (B). Line 5: max_dt.",
    "outputFormat": "One 'i j' per matched A index (0-based), in A order.",
    "tests": [
      {
        "input": "7\n0.0 0.033 0.066 0.10 0.133 0.166 0.20\n3\n0.005 0.105 0.205\n0.02\n",
        "expected": "0 0\n3 1\n6 2\n",
        "sample": true
      },
      {
        "input": "3\n0 1 2\n2\n0.1 5\n0.5\n",
        "expected": "0 0\n",
        "sample": true
      },
      {
        "input": "2\n0 10\n2\n0.1 9.9\n0.2\n",
        "expected": "0 0\n1 1\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    idx = 0\n    na = int(data[idx]); idx += 1\n    A = [float(data[idx+i]) for i in range(na)]; idx += na\n    nb = int(data[idx]); idx += 1\n    B = [float(data[idx+i]) for i in range(nb)]; idx += nb\n    max_dt = float(data[idx])\n    # TODO: print matched 'i j' pairs within max_dt\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int na; cin >> na; vector<double> A(na);\n    for (auto& v : A) cin >> v;\n    int nb; cin >> nb; vector<double> B(nb);\n    for (auto& v : B) cin >> v;\n    double max_dt; cin >> max_dt;\n    // TODO: print matched 'i j' pairs within max_dt\n    return 0;\n}\n"
    }
  },
  {
    "id": "rob-frame-ingest",
    "title": "Real-Time Frame Ingest Buffer",
    "diff": "Medium",
    "pattern": "Systems / Real-Time",
    "week": 9,
    "statement": "<p>On a drone, a camera callback ingests frames at 30&nbsp;Hz while a slower perception model consumes them asynchronously. Implement the <b>fixed-capacity ring buffer</b> between them: bounded memory (no growth in flight) with a <b>keep-latest</b> policy \u2014 when full, a <code>push</code> drops the <i>oldest</i> frame so the freshest data survives and latency stays bounded.</p><p>Support: <code>push x</code> (ingest frame id x; if full, drop the oldest and count it), <code>pop</code> (consumer takes the oldest buffered frame \u2014 print its id or <code>none</code>), <code>latest</code> (newest buffered id or <code>none</code>), <code>dropped</code> (how many were dropped on overflow), <code>size</code> (current count).</p>",
    "inputFormat": "Line 1: capacity. Line 2: q. Next q lines: 'push x', 'pop', 'latest', 'dropped', or 'size'.",
    "outputFormat": "One line per pop / latest / dropped / size query.",
    "tests": [
      {
        "input": "3\n8\npush 1\npush 2\npush 3\npush 4\npop\nlatest\ndropped\nsize\n",
        "expected": "2\n4\n1\n2\n",
        "sample": true
      },
      {
        "input": "2\n5\npush 10\npop\npop\nlatest\nsize\n",
        "expected": "10\nnone\nnone\n0\n",
        "sample": true
      },
      {
        "input": "2\n6\npush 5\npush 6\npush 7\nsize\nlatest\ndropped\n",
        "expected": "2\n7\n1\n",
        "sample": false
      }
    ],
    "category": "robotics",
    "checker": "exact",
    "tol": 0.0,
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    idx = 0\n    cap = int(data[idx]); idx += 1\n    q = int(data[idx]); idx += 1\n    out = []\n    # TODO: fixed-capacity ring buffer; keep-latest (drop oldest) when full\n    for _ in range(q):\n        cmd = data[idx]; idx += 1\n        if cmd == \"push\":\n            x = int(data[idx]); idx += 1\n            pass  # TODO\n        elif cmd == \"pop\":\n            pass  # TODO: out.append(oldest id or 'none')\n        elif cmd == \"latest\":\n            pass  # TODO\n        elif cmd == \"dropped\":\n            pass  # TODO\n        else:  # size\n            pass  # TODO\n    print(\"\\n\".join(out))\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int cap, q; cin >> cap >> q;\n    string cmd;\n    // TODO: fixed-capacity ring buffer (no dynamic growth); keep-latest on overflow\n    for (int i = 0; i < q; i++) {\n        cin >> cmd;\n        if (cmd == \"push\") { long long x; cin >> x; /* TODO */ }\n        else if (cmd == \"pop\") { /* TODO: print oldest id or \"none\" */ }\n        else if (cmd == \"latest\") { /* TODO */ }\n        else if (cmd == \"dropped\") { /* TODO */ }\n        else { /* size: TODO */ }\n    }\n    return 0;\n}\n"
    }
  }
];
