/* AUTO-GENERATED by gen_problems.py. Expected outputs verified by running
   reference solutions locally. Edit gen_problems.py and rerun to change. */
const PROBLEMS = [
  {
    "id": "two-sum",
    "title": "Two Sum",
    "diff": "Easy",
    "pattern": "Arrays / Hashing",
    "week": 1,
    "statement": "<p>Given an array of integers and a target, return the <b>indices</b> (0-based) of the two numbers that add up to the target. Exactly one solution exists; return the indices in ascending order.</p>",
    "inputFormat": "Line 1: n. Line 2: n integers. Line 3: target.",
    "outputFormat": "The two indices, space-separated, ascending.",
    "tests": [
      {
        "input": "4\n2 7 11 15\n9\n",
        "expected": "0 1\n",
        "sample": true
      },
      {
        "input": "3\n3 2 4\n6\n",
        "expected": "1 2\n",
        "sample": true
      },
      {
        "input": "2\n3 3\n6\n",
        "expected": "0 1\n",
        "sample": false
      },
      {
        "input": "5\n-1 -2 -3 -4 -5\n-8\n",
        "expected": "2 4\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    arr = list(map(int, data[1:1+n]))\n    target = int(data[1+n])\n    # TODO: print the two indices\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<int> a(n);\n    for (auto& x : a) cin >> x;\n    int target; cin >> target;\n    // TODO: print the two indices\n    return 0;\n}\n"
    }
  },
  {
    "id": "maximum-subarray",
    "title": "Maximum Subarray",
    "diff": "Medium",
    "pattern": "DP / Kadane",
    "week": 1,
    "statement": "<p>Find the contiguous subarray with the largest sum and return that sum.</p>",
    "inputFormat": "Line 1: n. Line 2: n integers.",
    "outputFormat": "The maximum subarray sum.",
    "tests": [
      {
        "input": "9\n-2 1 -3 4 -1 2 1 -5 4\n",
        "expected": "6\n",
        "sample": true
      },
      {
        "input": "1\n1\n",
        "expected": "1\n",
        "sample": true
      },
      {
        "input": "5\n5 4 -1 7 8\n",
        "expected": "23\n",
        "sample": false
      },
      {
        "input": "4\n-3 -2 -5 -1\n",
        "expected": "-1\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    arr = list(map(int, data[1:1+n]))\n    # TODO: print the maximum subarray sum\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<long long> a(n);\n    for (auto& x : a) cin >> x;\n    // TODO: print the maximum subarray sum\n    return 0;\n}\n"
    }
  },
  {
    "id": "product-except-self",
    "title": "Product of Array Except Self",
    "diff": "Medium",
    "pattern": "Arrays / Prefix",
    "week": 1,
    "statement": "<p>Return an array where each element is the product of all the others, <b>without using division</b>. O(n) time.</p>",
    "inputFormat": "Line 1: n. Line 2: n integers.",
    "outputFormat": "n integers (the answer), space-separated.",
    "tests": [
      {
        "input": "4\n1 2 3 4\n",
        "expected": "24 12 8 6\n",
        "sample": true
      },
      {
        "input": "5\n-1 1 0 -3 3\n",
        "expected": "0 0 9 0 0\n",
        "sample": true
      },
      {
        "input": "2\n2 3\n",
        "expected": "3 2\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    arr = list(map(int, data[1:1+n]))\n    # TODO: print the result array\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<long long> a(n);\n    for (auto& x : a) cin >> x;\n    // TODO: print the result array\n    return 0;\n}\n"
    }
  },
  {
    "id": "rotate-image",
    "title": "Rotate Image",
    "diff": "Medium",
    "pattern": "Matrix",
    "week": 2,
    "statement": "<p>Rotate an n\u00d7n matrix by 90\u00b0 <b>clockwise</b> and print the result.</p>",
    "inputFormat": "Line 1: n. Next n lines: n integers each.",
    "outputFormat": "The rotated matrix, n lines of n integers.",
    "tests": [
      {
        "input": "3\n1 2 3\n4 5 6\n7 8 9\n",
        "expected": "7 4 1\n8 5 2\n9 6 3\n",
        "sample": true
      },
      {
        "input": "2\n1 2\n3 4\n",
        "expected": "3 1\n4 2\n",
        "sample": true
      },
      {
        "input": "1\n7\n",
        "expected": "7\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    vals = list(map(int, data[1:1+n*n]))\n    m = [vals[i*n:(i+1)*n] for i in range(n)]\n    # TODO: rotate 90 deg clockwise and print\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<vector<int>> m(n, vector<int>(n));\n    for (auto& r : m) for (auto& x : r) cin >> x;\n    // TODO: rotate 90 deg clockwise and print\n    return 0;\n}\n"
    }
  },
  {
    "id": "spiral-matrix",
    "title": "Spiral Matrix",
    "diff": "Medium",
    "pattern": "Matrix",
    "week": 2,
    "statement": "<p>Return all elements of the matrix in <b>spiral order</b> (clockwise from top-left).</p>",
    "inputFormat": "Line 1: rows cols. Next rows lines: cols integers each.",
    "outputFormat": "All elements in spiral order, space-separated on one line.",
    "tests": [
      {
        "input": "3 3\n1 2 3\n4 5 6\n7 8 9\n",
        "expected": "1 2 3 6 9 8 7 4 5\n",
        "sample": true
      },
      {
        "input": "3 4\n1 2 3 4\n5 6 7 8\n9 10 11 12\n",
        "expected": "1 2 3 4 8 12 11 10 9 5 6 7\n",
        "sample": true
      },
      {
        "input": "1 1\n5\n",
        "expected": "5\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    rows = int(data[0]); cols = int(data[1])\n    vals = list(map(int, data[2:2+rows*cols]))\n    m = [vals[i*cols:(i+1)*cols] for i in range(rows)]\n    # TODO: print spiral order\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int rows, cols; cin >> rows >> cols;\n    vector<vector<int>> m(rows, vector<int>(cols));\n    for (auto& r : m) for (auto& x : r) cin >> x;\n    // TODO: print spiral order\n    return 0;\n}\n"
    }
  },
  {
    "id": "number-of-islands",
    "title": "Number of Islands",
    "diff": "Medium",
    "pattern": "Grid BFS/DFS",
    "week": 3,
    "statement": "<p>Count the islands in a grid of <code>'1'</code> (land) and <code>'0'</code> (water). Cells connect 4-directionally.</p>",
    "inputFormat": "Line 1: rows cols. Next rows lines: a string of cols characters ('0'/'1').",
    "outputFormat": "The number of islands.",
    "tests": [
      {
        "input": "4 5\n11110\n11010\n11000\n00000\n",
        "expected": "1\n",
        "sample": true
      },
      {
        "input": "3 3\n101\n010\n101\n",
        "expected": "5\n",
        "sample": true
      },
      {
        "input": "1 1\n0\n",
        "expected": "0\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split('\\n')\n    rows, cols = map(int, data[0].split())\n    grid = [list(data[1+i].strip()) for i in range(rows)]\n    # TODO: print the island count\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int rows, cols; cin >> rows >> cols;\n    vector<string> g(rows);\n    for (auto& s : g) cin >> s;\n    // TODO: print the island count\n    return 0;\n}\n"
    }
  },
  {
    "id": "image-smoother",
    "title": "Image Smoother",
    "diff": "Easy",
    "pattern": "Matrix / Convolution",
    "week": 3,
    "statement": "<p>For each cell output the floor of the average of itself and its (up to 8) neighbors \u2014 a 3\u00d73 box filter.</p>",
    "inputFormat": "Line 1: rows cols. Next rows lines: cols integers each.",
    "outputFormat": "The smoothed matrix, rows lines of cols integers.",
    "tests": [
      {
        "input": "3 3\n1 1 1\n1 0 1\n1 1 1\n",
        "expected": "0 0 0\n0 0 0\n0 0 0\n",
        "sample": true
      },
      {
        "input": "2 2\n100 200\n100 200\n",
        "expected": "150 150\n150 150\n",
        "sample": true
      },
      {
        "input": "1 3\n2 4 6\n",
        "expected": "3 4 5\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    rows = int(data[0]); cols = int(data[1])\n    vals = list(map(int, data[2:2+rows*cols]))\n    m = [vals[i*cols:(i+1)*cols] for i in range(rows)]\n    # TODO: print the smoothed matrix\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int rows, cols; cin >> rows >> cols;\n    vector<vector<int>> m(rows, vector<int>(cols));\n    for (auto& r : m) for (auto& x : r) cin >> x;\n    // TODO: print the smoothed matrix\n    return 0;\n}\n"
    }
  },
  {
    "id": "k-closest-points",
    "title": "K Closest Points to Origin",
    "diff": "Medium",
    "pattern": "Heap / Sorting",
    "week": 4,
    "statement": "<p>Return the k points closest to the origin (Euclidean). Break ties by x then y so the answer is deterministic; print sorted by (distance, x, y).</p>",
    "inputFormat": "Line 1: n. Next n lines: x y. Last line: k.",
    "outputFormat": "k lines, each 'x y', ordered by distance then x then y.",
    "tests": [
      {
        "input": "3\n1 3\n-2 2\n5 8\n2\n",
        "expected": "-2 2\n1 3\n",
        "sample": true
      },
      {
        "input": "2\n3 3\n5 -1\n1\n",
        "expected": "3 3\n",
        "sample": true
      },
      {
        "input": "4\n0 1\n1 0\n2 2\n-1 -1\n3\n",
        "expected": "0 1\n1 0\n-1 -1\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    pts = []\n    idx = 1\n    for _ in range(n):\n        pts.append((int(data[idx]), int(data[idx+1]))); idx += 2\n    k = int(data[idx])\n    # TODO: print the k closest points\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<pair<int,int>> p(n);\n    for (auto& q : p) cin >> q.first >> q.second;\n    int k; cin >> k;\n    // TODO: print the k closest points\n    return 0;\n}\n"
    }
  },
  {
    "id": "max-points-on-a-line",
    "title": "Max Points on a Line",
    "diff": "Hard",
    "pattern": "Geometry",
    "week": 4,
    "statement": "<p>Given n points on a plane, return the maximum number of points that lie on the same straight line.</p>",
    "inputFormat": "Line 1: n. Next n lines: x y.",
    "outputFormat": "The maximum number of collinear points.",
    "tests": [
      {
        "input": "6\n1 1\n2 2\n3 3\n1 4\n2 5\n3 6\n",
        "expected": "3\n",
        "sample": true
      },
      {
        "input": "3\n1 1\n3 2\n5 3\n",
        "expected": "3\n",
        "sample": true
      },
      {
        "input": "1\n0 0\n",
        "expected": "1\n",
        "sample": false
      },
      {
        "input": "4\n0 0\n1 1\n2 2\n3 3\n",
        "expected": "4\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    pts = []\n    idx = 1\n    for _ in range(n):\n        pts.append((int(data[idx]), int(data[idx+1]))); idx += 2\n    # TODO: print max points on a line\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<pair<int,int>> p(n);\n    for (auto& q : p) cin >> q.first >> q.second;\n    // TODO: print max points on a line\n    return 0;\n}\n"
    }
  },
  {
    "id": "moving-average",
    "title": "Moving Average from Data Stream",
    "diff": "Easy",
    "pattern": "Stream / Sliding Window",
    "week": 5,
    "statement": "<p>Maintain a moving average over a sliding window of the given size. For each incoming value, print the current average (5 decimals).</p>",
    "inputFormat": "Line 1: window size. Line 2: m (count). Line 3: m integers (the stream).",
    "outputFormat": "m lines, each the moving average formatted to 5 decimals.",
    "tests": [
      {
        "input": "3\n5\n1 10 3 5 20\n",
        "expected": "1.00000\n5.50000\n4.66667\n6.00000\n9.33333\n",
        "sample": true
      },
      {
        "input": "1\n3\n4 0 8\n",
        "expected": "4.00000\n0.00000\n8.00000\n",
        "sample": true
      },
      {
        "input": "2\n4\n2 2 2 2\n",
        "expected": "2.00000\n2.00000\n2.00000\n2.00000\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    size = int(data[0]); m = int(data[1])\n    vals = list(map(int, data[2:2+m]))\n    # TODO: print each moving average with '%.5f' % avg\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int size, m; cin >> size >> m;\n    vector<int> v(m);\n    for (auto& x : v) cin >> x;\n    cout << fixed << setprecision(5);\n    // TODO: print each moving average\n    return 0;\n}\n"
    }
  },
  {
    "id": "sliding-window-maximum",
    "title": "Sliding Window Maximum",
    "diff": "Hard",
    "pattern": "Monotonic Deque",
    "week": 5,
    "statement": "<p>Given an array and window size k, output the maximum of each contiguous window.</p>",
    "inputFormat": "Line 1: n. Line 2: n integers. Line 3: k.",
    "outputFormat": "The window maxima, space-separated.",
    "tests": [
      {
        "input": "8\n1 3 -1 -3 5 3 6 7\n3\n",
        "expected": "3 3 5 5 6 7\n",
        "sample": true
      },
      {
        "input": "1\n1\n1\n",
        "expected": "1\n",
        "sample": true
      },
      {
        "input": "6\n9 8 7 6 5 4\n2\n",
        "expected": "9 8 7 6 5\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    a = list(map(int, data[1:1+n]))\n    k = int(data[1+n])\n    # TODO: print the window maxima\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<int> a(n);\n    for (auto& x : a) cin >> x;\n    int k; cin >> k;\n    // TODO: print the window maxima\n    return 0;\n}\n"
    }
  },
  {
    "id": "course-schedule",
    "title": "Course Schedule",
    "diff": "Medium",
    "pattern": "Graph / Topo Sort",
    "week": 6,
    "statement": "<p>There are numCourses courses. Each edge 'a b' means course a depends on course b. Determine if all courses can be finished (no cycle).</p>",
    "inputFormat": "Line 1: numCourses. Line 2: e (edges). Next e lines: a b.",
    "outputFormat": "'true' or 'false'.",
    "tests": [
      {
        "input": "2\n1\n1 0\n",
        "expected": "true\n",
        "sample": true
      },
      {
        "input": "2\n2\n1 0\n0 1\n",
        "expected": "false\n",
        "sample": true
      },
      {
        "input": "4\n3\n1 0\n2 1\n3 2\n",
        "expected": "true\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0]); e = int(data[1])\n    edges = []\n    idx = 2\n    for _ in range(e):\n        edges.append((int(data[idx]), int(data[idx+1]))); idx += 2\n    # TODO: print 'true' or 'false'\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n, e; cin >> n >> e;\n    vector<pair<int,int>> edges(e);\n    for (auto& p : edges) cin >> p.first >> p.second;\n    // TODO: print \"true\" or \"false\"\n    return 0;\n}\n"
    }
  },
  {
    "id": "network-delay-time",
    "title": "Network Delay Time",
    "diff": "Medium",
    "pattern": "Dijkstra",
    "week": 6,
    "statement": "<p>A signal starts at node k in a network of n nodes (1-indexed). Each directed edge 'u v w' has travel time w. Return the time for all nodes to receive the signal, or -1 if impossible.</p>",
    "inputFormat": "Line 1: n m k. Next m lines: u v w.",
    "outputFormat": "The delay time, or -1.",
    "tests": [
      {
        "input": "4 4 2\n2 1 1\n2 3 1\n3 4 1\n1 4 5\n",
        "expected": "2\n",
        "sample": true
      },
      {
        "input": "2 1 1\n1 2 1\n",
        "expected": "1\n",
        "sample": true
      },
      {
        "input": "2 1 2\n1 2 1\n",
        "expected": "-1\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0]); m = int(data[1]); k = int(data[2])\n    edges = []\n    idx = 3\n    for _ in range(m):\n        edges.append((int(data[idx]), int(data[idx+1]), int(data[idx+2]))); idx += 3\n    # TODO: print the delay time or -1\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n, m, k; cin >> n >> m >> k;\n    vector<array<int,3>> edges(m);\n    for (auto& e : edges) cin >> e[0] >> e[1] >> e[2];\n    // TODO: print the delay time or -1\n    return 0;\n}\n"
    }
  },
  {
    "id": "maximal-square",
    "title": "Maximal Square",
    "diff": "Medium",
    "pattern": "DP / Grid",
    "week": 7,
    "statement": "<p>In a binary grid, find the largest square containing only 1s and return its <b>area</b>.</p>",
    "inputFormat": "Line 1: rows cols. Next rows lines: a string of cols characters ('0'/'1').",
    "outputFormat": "The area of the largest all-ones square.",
    "tests": [
      {
        "input": "4 5\n10100\n10111\n11111\n10010\n",
        "expected": "4\n",
        "sample": true
      },
      {
        "input": "2 2\n01\n10\n",
        "expected": "1\n",
        "sample": true
      },
      {
        "input": "1 1\n0\n",
        "expected": "0\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split('\\n')\n    rows, cols = map(int, data[0].split())\n    grid = [data[1+i].strip() for i in range(rows)]\n    # TODO: print the maximal square area\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int rows, cols; cin >> rows >> cols;\n    vector<string> g(rows);\n    for (auto& s : g) cin >> s;\n    // TODO: print the maximal square area\n    return 0;\n}\n"
    }
  },
  {
    "id": "word-ladder",
    "title": "Word Ladder",
    "diff": "Hard",
    "pattern": "BFS",
    "week": 7,
    "statement": "<p>Return the number of words in the shortest transformation sequence from beginWord to endWord, changing one letter at a time, where each intermediate word must be in the word list. Return 0 if impossible. (Length counts both endpoints.)</p>",
    "inputFormat": "Line 1: beginWord. Line 2: endWord. Line 3: count. Next count lines: the word list.",
    "outputFormat": "The length of the shortest sequence, or 0.",
    "tests": [
      {
        "input": "hit\ncog\n6\nhot\ndot\ndog\nlot\nlog\ncog\n",
        "expected": "5\n",
        "sample": true
      },
      {
        "input": "hit\ncog\n5\nhot\ndot\ndog\nlot\nlog\n",
        "expected": "0\n",
        "sample": true
      },
      {
        "input": "a\nc\n2\nb\nc\n",
        "expected": "2\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    lines = sys.stdin.read().split('\\n')\n    begin = lines[0].strip(); end = lines[1].strip()\n    cnt = int(lines[2])\n    words = [lines[3+i].strip() for i in range(cnt)]\n    # TODO: print shortest ladder length or 0\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    string begin, end; cin >> begin >> end;\n    int cnt; cin >> cnt;\n    vector<string> words(cnt);\n    for (auto& w : words) cin >> w;\n    // TODO: print shortest ladder length or 0\n    return 0;\n}\n"
    }
  },
  {
    "id": "merge-intervals",
    "title": "Merge Intervals",
    "diff": "Medium",
    "pattern": "Intervals",
    "week": 8,
    "statement": "<p>Merge all overlapping intervals and print them sorted by start.</p>",
    "inputFormat": "Line 1: n. Next n lines: start end.",
    "outputFormat": "The merged intervals, one 'start end' per line, sorted by start.",
    "tests": [
      {
        "input": "4\n1 3\n2 6\n8 10\n15 18\n",
        "expected": "1 6\n8 10\n15 18\n",
        "sample": true
      },
      {
        "input": "2\n1 4\n4 5\n",
        "expected": "1 5\n",
        "sample": true
      },
      {
        "input": "3\n1 4\n0 4\n2 3\n",
        "expected": "0 4\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    iv = []\n    idx = 1\n    for _ in range(n):\n        iv.append((int(data[idx]), int(data[idx+1]))); idx += 2\n    # TODO: print merged intervals\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n;\n    vector<pair<int,int>> iv(n);\n    for (auto& p : iv) cin >> p.first >> p.second;\n    // TODO: print merged intervals\n    return 0;\n}\n"
    }
  },
  {
    "id": "set-matrix-zeroes",
    "title": "Set Matrix Zeroes",
    "diff": "Medium",
    "pattern": "Matrix",
    "week": 2,
    "statement": "<p>If an element is 0, set its entire row and column to 0 \u2014 and print the result. (Classic follow-up: do it in O(1) extra space.)</p>",
    "inputFormat": "Line 1: rows cols. Next rows lines: cols integers each.",
    "outputFormat": "The modified matrix, rows lines of cols integers.",
    "tests": [
      {
        "input": "3 3\n1 1 1\n1 0 1\n1 1 1\n",
        "expected": "1 0 1\n0 0 0\n1 0 1\n",
        "sample": true
      },
      {
        "input": "3 4\n0 1 2 0\n3 4 5 2\n1 3 1 5\n",
        "expected": "0 0 0 0\n0 4 5 0\n0 3 1 0\n",
        "sample": true
      },
      {
        "input": "1 1\n5\n",
        "expected": "5\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    rows = int(data[0]); cols = int(data[1])\n    vals = list(map(int, data[2:2+rows*cols]))\n    m = [vals[i*cols:(i+1)*cols] for i in range(rows)]\n    # TODO: zero out rows/cols and print the matrix\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int rows, cols; cin >> rows >> cols;\n    vector<vector<int>> m(rows, vector<int>(cols));\n    for (auto& r : m) for (auto& x : r) cin >> x;\n    // TODO: zero out rows/cols and print the matrix\n    return 0;\n}\n"
    }
  },
  {
    "id": "pacific-atlantic",
    "title": "Pacific Atlantic Water Flow",
    "diff": "Medium",
    "pattern": "Grid DFS/BFS",
    "week": 3,
    "statement": "<p>Water flows from a cell to a 4-neighbor with height <b>less than or equal</b> to it. The Pacific touches the top and left edges; the Atlantic touches the bottom and right edges. Print all cells from which water can reach <b>both</b> oceans.</p>",
    "inputFormat": "Line 1: m n. Next m lines: n integers (heights).",
    "outputFormat": "Each qualifying cell as 'row col' (0-indexed), one per line, sorted by row then col.",
    "tests": [
      {
        "input": "5 5\n1 2 2 3 5\n3 2 3 4 4\n2 4 5 3 1\n6 7 1 4 5\n5 1 1 2 4\n",
        "expected": "0 4\n1 3\n1 4\n2 2\n3 0\n3 1\n4 0\n",
        "sample": true
      },
      {
        "input": "1 1\n1\n",
        "expected": "0 0\n",
        "sample": true
      },
      {
        "input": "3 3\n1 2 3\n8 9 4\n7 6 5\n",
        "expected": "0 2\n1 0\n1 1\n1 2\n2 0\n2 1\n2 2\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    m = int(data[0]); n = int(data[1])\n    vals = list(map(int, data[2:2+m*n]))\n    h = [vals[i*n:(i+1)*n] for i in range(m)]\n    # TODO: print cells (row col) that reach both oceans, sorted\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int m, n; cin >> m >> n;\n    vector<vector<int>> h(m, vector<int>(n));\n    for (auto& r : h) for (auto& x : r) cin >> x;\n    // TODO: print cells (row col) that reach both oceans, sorted\n    return 0;\n}\n"
    }
  },
  {
    "id": "find-k-closest-elements",
    "title": "Find K Closest Elements",
    "diff": "Medium",
    "pattern": "Binary Search",
    "week": 4,
    "statement": "<p>Given a <b>sorted</b> array, return the k elements closest to x, in ascending order. Closeness is |a-x|; ties prefer the smaller value.</p>",
    "inputFormat": "Line 1: n. Line 2: n integers (ascending). Line 3: k x.",
    "outputFormat": "The k closest elements, ascending, space-separated.",
    "tests": [
      {
        "input": "5\n1 2 3 4 5\n4 3\n",
        "expected": "1 2 3 4\n",
        "sample": true
      },
      {
        "input": "5\n1 2 3 4 5\n4 -1\n",
        "expected": "1 2 3 4\n",
        "sample": true
      },
      {
        "input": "6\n1 1 1 10 10 10\n1 9\n",
        "expected": "10\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0])\n    a = list(map(int, data[1:1+n]))\n    k = int(data[1+n]); x = int(data[2+n])\n    # TODO: print the k closest elements (ascending)\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n; cin >> n; vector<int> a(n);\n    for (auto& v : a) cin >> v;\n    int k, x; cin >> k >> x;\n    // TODO: print the k closest elements (ascending)\n    return 0;\n}\n"
    }
  },
  {
    "id": "find-median-from-data-stream",
    "title": "Find Median from Data Stream",
    "diff": "Hard",
    "pattern": "Two Heaps",
    "week": 5,
    "statement": "<p>Process a stream of operations. <code>add x</code> inserts a number; <code>median</code> queries the current median. For each <code>median</code>, print the median formatted to <b>one decimal</b> (e.g. <code>2.0</code>, <code>2.5</code>).</p>",
    "inputFormat": "Line 1: q (operations). Next q lines: 'add x' or 'median'.",
    "outputFormat": "One line per 'median' query: the median to 1 decimal.",
    "tests": [
      {
        "input": "5\nadd 1\nadd 2\nmedian\nadd 3\nmedian\n",
        "expected": "1.5\n2.0\n",
        "sample": true
      },
      {
        "input": "4\nadd 5\nmedian\nadd 1\nmedian\n",
        "expected": "5.0\n3.0\n",
        "sample": true
      },
      {
        "input": "3\nadd 2\nadd 2\nmedian\n",
        "expected": "2.0\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    idx = 0\n    q = int(data[idx]); idx += 1\n    out = []\n    # TODO: maintain a structure (e.g. two heaps)\n    for _ in range(q):\n        cmd = data[idx]; idx += 1\n        if cmd == \"add\":\n            x = int(data[idx]); idx += 1\n            pass  # TODO: add x\n        else:\n            pass  # TODO: out.append('%.1f' % median)\n    print(\"\\n\".join(out))\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int q; cin >> q;\n    cout << fixed << setprecision(1);\n    string cmd;\n    // TODO: maintain a structure (e.g. two heaps)\n    for (int i = 0; i < q; i++) {\n        cin >> cmd;\n        if (cmd == \"add\") { long long x; cin >> x; /* TODO */ }\n        else { /* TODO: print median */ }\n    }\n    return 0;\n}\n"
    }
  },
  {
    "id": "graph-valid-tree",
    "title": "Graph Valid Tree",
    "diff": "Medium",
    "pattern": "Union-Find",
    "week": 6,
    "statement": "<p>Given n nodes (0..n-1) and an undirected edge list, decide whether the graph forms a <b>valid tree</b> (fully connected and acyclic).</p>",
    "inputFormat": "Line 1: n m. Next m lines: u v.",
    "outputFormat": "'true' or 'false'.",
    "tests": [
      {
        "input": "5\n4\n0 1\n0 2\n0 3\n1 4\n",
        "expected": "true\n",
        "sample": true
      },
      {
        "input": "5\n5\n0 1\n1 2\n2 3\n1 3\n1 4\n",
        "expected": "false\n",
        "sample": true
      },
      {
        "input": "4\n2\n0 1\n2 3\n",
        "expected": "false\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    n = int(data[0]); m = int(data[1])\n    edges = []\n    idx = 2\n    for _ in range(m):\n        edges.append((int(data[idx]), int(data[idx+1]))); idx += 2\n    # TODO: print 'true' if it is a valid tree else 'false'\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int n, m; cin >> n >> m;\n    vector<pair<int,int>> edges(m);\n    for (auto& e : edges) cin >> e.first >> e.second;\n    // TODO: print \"true\" or \"false\"\n    return 0;\n}\n"
    }
  },
  {
    "id": "lru-cache",
    "title": "LRU Cache",
    "diff": "Medium",
    "pattern": "Design / Hash + List",
    "week": 7,
    "statement": "<p>Implement an LRU cache with the given capacity. <code>put k v</code> inserts/updates; <code>get k</code> returns the value or -1 and marks it most-recently-used. Evict the least-recently-used item when over capacity. Print the result of every <code>get</code>.</p>",
    "inputFormat": "Line 1: capacity. Line 2: q. Next q lines: 'put k v' or 'get k'.",
    "outputFormat": "One line per 'get': the value, or -1.",
    "tests": [
      {
        "input": "2\n6\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 2\nget 3\n",
        "expected": "1\n-1\n3\n",
        "sample": true
      },
      {
        "input": "1\n4\nput 1 10\nget 1\nput 2 20\nget 1\n",
        "expected": "10\n-1\n",
        "sample": true
      },
      {
        "input": "2\n3\nget 5\nput 5 5\nget 5\n",
        "expected": "-1\n5\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    idx = 0\n    cap = int(data[idx]); idx += 1\n    q = int(data[idx]); idx += 1\n    out = []\n    # TODO: build the LRU cache (capacity = cap)\n    for _ in range(q):\n        cmd = data[idx]; idx += 1\n        if cmd == \"put\":\n            k = int(data[idx]); v = int(data[idx+1]); idx += 2\n            pass  # TODO: put k, v\n        else:\n            k = int(data[idx]); idx += 1\n            pass  # TODO: out.append(str(get(k)))\n    print(\"\\n\".join(out))\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int cap, q; cin >> cap >> q;\n    string cmd;\n    // TODO: build the LRU cache (capacity = cap)\n    for (int i = 0; i < q; i++) {\n        cin >> cmd;\n        if (cmd == \"put\") { int k, v; cin >> k >> v; /* TODO */ }\n        else { int k; cin >> k; /* TODO: print get(k) */ }\n    }\n    return 0;\n}\n"
    }
  },
  {
    "id": "design-circular-queue",
    "title": "Design Circular Queue",
    "diff": "Medium",
    "pattern": "Design / Ring Buffer",
    "week": 8,
    "statement": "<p>Implement a circular queue of capacity k. Operations: <code>enQueue x</code>, <code>deQueue</code>, <code>Front</code>, <code>Rear</code>, <code>isEmpty</code>, <code>isFull</code>. enQueue/deQueue print <code>true</code>/<code>false</code>; Front/Rear print the value or -1; isEmpty/isFull print <code>true</code>/<code>false</code>. Print the result of every operation.</p>",
    "inputFormat": "Line 1: k (capacity). Line 2: q. Next q lines: an operation (with an arg for enQueue).",
    "outputFormat": "One line per operation: its return value.",
    "tests": [
      {
        "input": "3\n7\nenQueue 1\nenQueue 2\nenQueue 3\nenQueue 4\nRear\nisFull\ndeQueue\n",
        "expected": "true\ntrue\ntrue\nfalse\n3\ntrue\ntrue\n",
        "sample": true
      },
      {
        "input": "2\n4\nisEmpty\nenQueue 5\nFront\ndeQueue\n",
        "expected": "true\ntrue\n5\ntrue\n",
        "sample": true
      },
      {
        "input": "1\n3\nenQueue 9\nRear\ndeQueue\n",
        "expected": "true\n9\ntrue\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    idx = 0\n    k = int(data[idx]); idx += 1\n    q = int(data[idx]); idx += 1\n    out = []\n    # TODO: build the circular queue (capacity = k)\n    for _ in range(q):\n        cmd = data[idx]; idx += 1\n        if cmd == \"enQueue\":\n            x = int(data[idx]); idx += 1\n            pass  # TODO: out.append('true'/'false')\n        else:\n            pass  # TODO: handle deQueue/Front/Rear/isEmpty/isFull\n    print(\"\\n\".join(out))\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int k, q; cin >> k >> q;\n    string cmd;\n    // TODO: build the circular queue (capacity = k)\n    for (int i = 0; i < q; i++) {\n        cin >> cmd;\n        if (cmd == \"enQueue\") { int x; cin >> x; /* TODO */ }\n        else { /* TODO: deQueue/Front/Rear/isEmpty/isFull */ }\n    }\n    return 0;\n}\n"
    }
  },
  {
    "id": "time-based-key-value-store",
    "title": "Time-Based Key-Value Store",
    "diff": "Medium",
    "pattern": "Design / Binary Search",
    "week": 8,
    "statement": "<p>Implement a store where <code>set key value ts</code> stores a value at timestamp ts (timestamps strictly increase per key), and <code>get key ts</code> returns the value with the largest timestamp \u2264 ts, or an empty string if none. Print every <code>get</code> result.</p>",
    "inputFormat": "Line 1: q. Next q lines: 'set key value ts' or 'get key ts'. (key/value are single tokens.)",
    "outputFormat": "One line per 'get': the value, or an empty line if none.",
    "tests": [
      {
        "input": "5\nset foo bar 1\nget foo 1\nget foo 3\nset foo baz 4\nget foo 4\n",
        "expected": "bar\nbar\nbaz\n",
        "sample": true
      },
      {
        "input": "3\nget x 1\nset x a 5\nget x 10\n",
        "expected": "\na\n",
        "sample": true
      },
      {
        "input": "4\nset k v1 1\nset k v2 2\nget k 1\nget k 2\n",
        "expected": "v1\nv2\n",
        "sample": false
      }
    ],
    "starter": {
      "python": "import sys\n\ndef main():\n    data = sys.stdin.read().split()\n    idx = 0\n    q = int(data[idx]); idx += 1\n    out = []\n    # TODO: build the time-based store\n    for _ in range(q):\n        cmd = data[idx]; idx += 1\n        if cmd == \"set\":\n            key = data[idx]; val = data[idx+1]; ts = int(data[idx+2]); idx += 3\n            pass  # TODO: set\n        else:\n            key = data[idx]; ts = int(data[idx+1]); idx += 2\n            pass  # TODO: out.append(get(key, ts))\n    print(\"\\n\".join(out))\n\nmain()\n",
      "cpp": "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false); cin.tie(nullptr);\n    int q; cin >> q;\n    string cmd;\n    // TODO: build the time-based store\n    for (int i = 0; i < q; i++) {\n        cin >> cmd;\n        if (cmd == \"set\") { string key, val; int ts; cin >> key >> val >> ts; /* TODO */ }\n        else { string key; int ts; cin >> key >> ts; /* TODO: print get */ }\n    }\n    return 0;\n}\n"
    }
  }
];
